/*
 * Copyright 2025 ByteChef
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bytechef.ai.tool.facade;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import com.bytechef.ai.tool.FromAiResult;
import com.bytechef.evaluator.Evaluator;
import com.bytechef.test.extension.ObjectMapperSetupExtension;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * @author Ivica Cardic
 */
@ExtendWith({
    MockitoExtension.class, ObjectMapperSetupExtension.class
})
class AbstractToolFacadeTest {

    @Mock
    private Evaluator evaluator;

    private AbstractToolFacade createToolFacade() {
        return new AbstractToolFacade(evaluator) {};
    }

    @Test
    void testExtractFromAiResultsWithSingleFromAiExpression() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('subject')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("subject", null, "STRING", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        List<FromAiResult> results = toolFacade.extractFromAiResults(Map.of("title", "=fromAi('subject')"));

        assertEquals(1, results.size());
        assertEquals("subject", results.getFirst()
            .name());
    }

    @Test
    void testExtractFromAiResultsWithMultipleFromAiCallsInOneExpression() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('subject')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("subject", null, "STRING", null)));
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('name')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("name", null, "STRING", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        List<FromAiResult> results = toolFacade.extractFromAiResults(
            Map.of("title", "='Generated by AI: ' + fromAi('subject') + ' by ' + fromAi('name')"));

        assertEquals(2, results.size());
        assertEquals("subject", results.get(0)
            .name());
        assertEquals("name", results.get(1)
            .name());
    }

    @Test
    void testExtractFromAiResultsDeduplicatesByName() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('subject')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("subject", null, "STRING", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        Map<String, Object> parameters = new LinkedHashMap<>();

        parameters.put("title", "='Title: ' + fromAi('subject')");
        parameters.put("body", "=fromAi('subject') + ' details'");

        List<FromAiResult> results = toolFacade.extractFromAiResults(parameters);

        assertEquals(1, results.size());
        assertEquals("subject", results.getFirst()
            .name());
    }

    @Test
    void testExtractFromAiResultsWithFromAiResultObjectValue() {
        AbstractToolFacade toolFacade = createToolFacade();

        FromAiResult directResult = new FromAiResult("directParam", "A direct param", "STRING", null);

        List<FromAiResult> results = toolFacade.extractFromAiResults(Map.of("param", directResult));

        assertEquals(1, results.size());

        FromAiResult firstResult = results.getFirst();

        assertEquals("directParam", firstResult.name());
    }

    @Test
    void testExtractFromAiResultsWithMapConvertibleToFromAiResult() {
        AbstractToolFacade toolFacade = createToolFacade();

        Map<String, Object> fromAiResultMap = new LinkedHashMap<>();

        fromAiResultMap.put("name", "mapParam");
        fromAiResultMap.put("description", "A map-based param");
        fromAiResultMap.put("type", "STRING");
        fromAiResultMap.put("defaultValue", null);

        List<FromAiResult> results = toolFacade.extractFromAiResults(Map.of("param", fromAiResultMap));

        assertEquals(1, results.size());
        assertEquals("mapParam", results.getFirst()
            .name());
        assertEquals("A map-based param", results.getFirst()
            .description());
    }

    @Test
    void testExtractFromAiResultsWithMapConvertibleToFromAiResultDeduplicatesWithDirectResult() {
        AbstractToolFacade toolFacade = createToolFacade();

        FromAiResult directResult = new FromAiResult("sharedName", "Direct", "STRING", null);

        Map<String, Object> fromAiResultMap = new LinkedHashMap<>();

        fromAiResultMap.put("name", "sharedName");
        fromAiResultMap.put("description", "From map");
        fromAiResultMap.put("type", "STRING");
        fromAiResultMap.put("defaultValue", null);

        Map<String, Object> parameters = new LinkedHashMap<>();

        parameters.put("first", directResult);
        parameters.put("second", fromAiResultMap);

        List<FromAiResult> results = toolFacade.extractFromAiResults(parameters);

        assertEquals(1, results.size());
        assertEquals("Direct", results.getFirst()
            .description());
    }

    @Test
    void testExtractFromAiResultsWithListOfFromAiExpressions() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('Email__0', 'STRING', {'description': 'The attendee email address.'})")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("Email__0", "The attendee email address.", "STRING", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        List<FromAiResult> results = toolFacade.extractFromAiResults(
            Map.of("attendees", List.of("=fromAi('Email__0', 'STRING', {'description': 'The attendee email address.'})")));

        assertEquals(1, results.size());
        assertEquals("Email__0", results.getFirst()
            .name());
        assertEquals("The attendee email address.", results.getFirst()
            .description());
    }

    @Test
    void testExtractFromAiResultsWithListOfPreEvaluatedFromAiResultMaps() {
        AbstractToolFacade toolFacade = createToolFacade();

        Map<String, Object> fromAiResultMap = new LinkedHashMap<>();

        fromAiResultMap.put("name", "Email__0");
        fromAiResultMap.put("description", "The attendee's email address.");
        fromAiResultMap.put("type", "STRING");
        fromAiResultMap.put("defaultValue", null);
        fromAiResultMap.put("options", null);

        List<FromAiResult> results = toolFacade.extractFromAiResults(
            Map.of("attendees", List.of(fromAiResultMap)));

        assertEquals(1, results.size());
        assertEquals("Email__0", results.getFirst()
            .name());
        assertEquals("The attendee's email address.", results.getFirst()
            .description());
    }

    @Test
    void testExtractFromAiResultsWithNonFromAiParameters() {
        AbstractToolFacade toolFacade = createToolFacade();

        List<FromAiResult> results = toolFacade.extractFromAiResults(
            Map.of("title", "plain text", "count", 42));

        assertEquals(0, results.size());
    }

    @Test
    void testExtractFromAiResultsWithNullParameters() {
        AbstractToolFacade toolFacade = createToolFacade();

        List<FromAiResult> results = toolFacade.extractFromAiResults(null);

        assertEquals(0, results.size());
    }

    @Test
    void testResolveParameterValueWithFromAiResultObject() {
        AbstractToolFacade toolFacade = createToolFacade();

        FromAiResult fromAiResult = new FromAiResult("subject", null, "STRING", null);

        Object result = toolFacade.resolveParameterValue(fromAiResult, Map.of("subject", "Hello World"));

        assertEquals("Hello World", result);
    }

    @Test
    void testResolveParameterValueWithFromAiResultObjectFallsBackToDefault() {
        AbstractToolFacade toolFacade = createToolFacade();

        FromAiResult fromAiResult = new FromAiResult("subject", null, "STRING", "default value");

        Object result = toolFacade.resolveParameterValue(fromAiResult, Map.of());

        assertEquals("default value", result);
    }

    @Test
    void testResolveParameterValueWithFromAiResultObjectReturnsNullWhenNoDefaultAndNotInRequest() {
        AbstractToolFacade toolFacade = createToolFacade();

        FromAiResult fromAiResult = new FromAiResult("subject", null, "STRING", null);

        Object result = toolFacade.resolveParameterValue(fromAiResult, Map.of());

        assertNull(result);
    }

    @Test
    void testResolveParameterValueWithMapConvertibleToFromAiResult() {
        AbstractToolFacade toolFacade = createToolFacade();

        Map<String, Object> fromAiResultMap = new LinkedHashMap<>();

        fromAiResultMap.put("name", "subject");
        fromAiResultMap.put("description", null);
        fromAiResultMap.put("type", "STRING");
        fromAiResultMap.put("defaultValue", null);

        Object result = toolFacade.resolveParameterValue(fromAiResultMap, Map.of("subject", "Resolved Value"));

        assertEquals("Resolved Value", result);
    }

    @Test
    void testResolveParameterValueWithMapConvertibleToFromAiResultFallsBackToDefault() {
        AbstractToolFacade toolFacade = createToolFacade();

        Map<String, Object> fromAiResultMap = new LinkedHashMap<>();

        fromAiResultMap.put("name", "subject");
        fromAiResultMap.put("description", null);
        fromAiResultMap.put("type", "STRING");
        fromAiResultMap.put("defaultValue", "fallback");

        Object result = toolFacade.resolveParameterValue(fromAiResultMap, Map.of());

        assertEquals("fallback", result);
    }

    @Test
    void testResolveParameterValueWithMapConvertibleToFromAiResultReturnsNullWhenNoDefault() {
        AbstractToolFacade toolFacade = createToolFacade();

        Map<String, Object> fromAiResultMap = new LinkedHashMap<>();

        fromAiResultMap.put("name", "subject");
        fromAiResultMap.put("description", null);
        fromAiResultMap.put("type", "STRING");
        fromAiResultMap.put("defaultValue", null);

        Object result = toolFacade.resolveParameterValue(fromAiResultMap, Map.of());

        assertNull(result);
    }

    @Test
    void testResolveParameterValueWithPureFromAiExpression() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('subject')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("subject", null, "STRING", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue("=fromAi('subject')", Map.of("subject", "Hello World"));

        assertEquals("Hello World", result);
    }

    @Test
    void testResolveParameterValueWithPureFromAiExpressionPreservesIntegerType() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('count', null, 'INTEGER')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("count", null, "INTEGER", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue(
            "=fromAi('count', null, 'INTEGER')", Map.of("count", 42));

        assertEquals(42, result);
    }

    @Test
    void testResolveParameterValueWithCompositeExpression() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('subject')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("subject", null, "STRING", null)));
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('name')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("name", null, "STRING", null)));
        when(evaluator.evaluate(
            eq(Map.of("value", "='Generated by AI: ' + 'Hello World' + ' by ' + 'John'")), eq(Map.of())))
                .thenReturn(Map.of("value", "Generated by AI: Hello World by John"));

        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue(
            "='Generated by AI: ' + fromAi('subject') + ' by ' + fromAi('name')",
            Map.of("subject", "Hello World", "name", "John"));

        assertEquals("Generated by AI: Hello World by John", result);
    }

    @Test
    void testResolveParameterValueWithCompositeExpressionUsesDefaults() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('subject')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("subject", null, "STRING", "Default Subject")));
        when(evaluator.evaluate(eq(Map.of("value", "='Title: ' + 'Default Subject'")), eq(Map.of())))
            .thenReturn(Map.of("value", "Title: Default Subject"));

        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue("='Title: ' + fromAi('subject')", Map.of());

        assertEquals("Title: Default Subject", result);
    }

    @Test
    void testResolveParameterValueWithListOfFromAiExpressions() {
        when(evaluator.evaluate(eq(Map.of("value", "=fromAi('Email__0')")), eq(Map.of())))
            .thenReturn(Map.of("value", new FromAiResult("Email__0", null, "STRING", null)));

        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue(
            List.of("=fromAi('Email__0')"), Map.of("Email__0", "user@example.com"));

        assertEquals(List.of("user@example.com"), result);
    }

    @Test
    void testResolveParameterValueWithNonFromAiStringValue() {
        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue("plain text", Map.of());

        assertEquals("plain text", result);
    }

    @Test
    void testResolveParameterValueWithNonStringValue() {
        AbstractToolFacade toolFacade = createToolFacade();

        Object result = toolFacade.resolveParameterValue(42, Map.of());

        assertEquals(42, result);
    }

    @Test
    void testExtractFromAiCallStringsSingleCall() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings("=fromAi('subject')");

        assertEquals(List.of("fromAi('subject')"), calls);
    }

    @Test
    void testExtractFromAiCallStringsSingleCallWithMultipleArgs() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings(
            "=fromAi('count', 'Number of items', 'INTEGER', 10)");

        assertEquals(List.of("fromAi('count', 'Number of items', 'INTEGER', 10)"), calls);
    }

    @Test
    void testExtractFromAiCallStringsMultipleCalls() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings(
            "='Generated by AI: ' + fromAi('subject') + ' by ' + fromAi('name')");

        assertEquals(List.of("fromAi('subject')", "fromAi('name')"), calls);
    }

    @Test
    void testExtractFromAiCallStringsThreeCalls() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings(
            "=fromAi('greeting') + ' ' + fromAi('name') + ', ' + fromAi('message')");

        assertEquals(List.of("fromAi('greeting')", "fromAi('name')", "fromAi('message')"), calls);
    }

    @Test
    void testExtractFromAiCallStringsNoCallsPlainText() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings("='plain text'");

        assertEquals(List.of(), calls);
    }

    @Test
    void testExtractFromAiCallStringsNoCallsEmptyString() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings("");

        assertEquals(List.of(), calls);
    }

    @Test
    void testExtractFromAiCallStringsWithEscapedQuotes() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings("=fromAi('it''s a name')");

        assertEquals(List.of("fromAi('it''s a name')"), calls);
    }

    @Test
    void testExtractFromAiCallStringsWithoutEqualsPrefix() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings("fromAi('subject')");

        assertEquals(List.of("fromAi('subject')"), calls);
    }

    @Test
    void testExtractFromAiCallStringsMixedWithArithmetic() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings(
            "=fromAi('count', null, 'INTEGER') + 10");

        assertEquals(List.of("fromAi('count', null, 'INTEGER')"), calls);
    }

    @Test
    void testExtractFromAiCallStringsWithNullArgument() {
        List<String> calls = AbstractToolFacade.extractFromAiCallStrings(
            "=fromAi('name', null, 'STRING', 'default')");

        assertEquals(List.of("fromAi('name', null, 'STRING', 'default')"), calls);
    }

    @Test
    void testToSpelLiteralNull() {
        assertEquals("null", AbstractToolFacade.toSpElLiteral(null));
    }

    @Test
    void testToSpelLiteralString() {
        assertEquals("'hello'", AbstractToolFacade.toSpElLiteral("hello"));
    }

    @Test
    void testToSpelLiteralStringWithQuotes() {
        assertEquals("'it''s fine'", AbstractToolFacade.toSpElLiteral("it's fine"));
    }

    @Test
    void testToSpelLiteralEmptyString() {
        assertEquals("''", AbstractToolFacade.toSpElLiteral(""));
    }

    @Test
    void testToSpelLiteralInteger() {
        assertEquals("42", AbstractToolFacade.toSpElLiteral(42));
    }

    @Test
    void testToSpelLiteralLong() {
        assertEquals("100", AbstractToolFacade.toSpElLiteral(100L));
    }

    @Test
    void testToSpelLiteralDouble() {
        assertEquals("3.75", AbstractToolFacade.toSpElLiteral(3.75));
    }

    @Test
    void testToSpelLiteralFloat() {
        assertEquals("2.5", AbstractToolFacade.toSpElLiteral(2.5f));
    }

    @Test
    void testToSpelLiteralBooleanTrue() {
        assertEquals("true", AbstractToolFacade.toSpElLiteral(true));
    }

    @Test
    void testToSpelLiteralBooleanFalse() {
        assertEquals("false", AbstractToolFacade.toSpElLiteral(false));
    }
}
