label: Http Client

tasks:
  - type: httpClient
    requestMethod: GET
    authenticationType: BASIC_AUTH
    uri: http://localhost:8080/o/headless-batch-engine/v1.0/export-task/701/content
    responseFormat: BINARY
    name: testResponse
    credentials:
      username: test@liferay.com
      password: 1234