/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisplayOptionModel } from './DisplayOptionModel';
import {
    DisplayOptionModelFromJSON,
    DisplayOptionModelFromJSONTyped,
    DisplayOptionModelToJSON,
} from './DisplayOptionModel';
import type { PropertyOptionModel } from './PropertyOptionModel';
import {
    PropertyOptionModelFromJSON,
    PropertyOptionModelFromJSONTyped,
    PropertyOptionModelToJSON,
} from './PropertyOptionModel';
import type { ValuePropertyModel } from './ValuePropertyModel';
import {
    ValuePropertyModelFromJSON,
    ValuePropertyModelFromJSONTyped,
    ValuePropertyModelToJSON,
} from './ValuePropertyModel';

/**
 * A boolean property type.
 * @export
 * @interface BooleanPropertyModel
 */
export interface BooleanPropertyModel extends ValuePropertyModel {
    /**
     * 
     * @type {string}
     * @memberof BooleanPropertyModel
     */
    type: string;
}

/**
 * Check if a given object implements the BooleanPropertyModel interface.
 */
export function instanceOfBooleanPropertyModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function BooleanPropertyModelFromJSON(json: any): BooleanPropertyModel {
    return BooleanPropertyModelFromJSONTyped(json, false);
}

export function BooleanPropertyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanPropertyModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ValuePropertyModelFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
    };
}

export function BooleanPropertyModelToJSON(value?: BooleanPropertyModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ValuePropertyModelToJSON(value),
        'type': value.type,
    };
}

