/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisplayOptionModel } from './DisplayOptionModel';
import {
    DisplayOptionModelFromJSON,
    DisplayOptionModelFromJSONTyped,
    DisplayOptionModelToJSON,
} from './DisplayOptionModel';
import type { PropertyModel } from './PropertyModel';
import {
    PropertyModelFromJSON,
    PropertyModelFromJSONTyped,
    PropertyModelToJSON,
} from './PropertyModel';
import type { PropertyTypeModel } from './PropertyTypeModel';
import {
    PropertyTypeModelFromJSON,
    PropertyTypeModelFromJSONTyped,
    PropertyTypeModelToJSON,
} from './PropertyTypeModel';

/**
 * A one of property type.
 * @export
 * @interface OneOfPropertyModel
 */
export interface OneOfPropertyModel extends PropertyModel {
    /**
     * Possible types of properties that can be used.
     * @type {Array<PropertyModel>}
     * @memberof OneOfPropertyModel
     */
    types?: Array<PropertyModel>;
}

/**
 * Check if a given object implements the OneOfPropertyModel interface.
 */
export function instanceOfOneOfPropertyModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OneOfPropertyModelFromJSON(json: any): OneOfPropertyModel {
    return OneOfPropertyModelFromJSONTyped(json, false);
}

export function OneOfPropertyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneOfPropertyModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...PropertyModelFromJSONTyped(json, ignoreDiscriminator),
        'types': !exists(json, 'types') ? undefined : ((json['types'] as Array<any>).map(PropertyModelFromJSON)),
    };
}

export function OneOfPropertyModelToJSON(value?: OneOfPropertyModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...PropertyModelToJSON(value),
        'types': value.types === undefined ? undefined : ((value.types as Array<any>).map(PropertyModelToJSON)),
    };
}

