/* tslint:disable */
/* eslint-disable */
/**
 * The Automation API Platform Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiClient200Response
 */
export interface CreateApiClient200Response {
    /**
     * The secret API key.
     * @type {string}
     * @memberof CreateApiClient200Response
     */
    secretKey?: string;
}

/**
 * Check if a given object implements the CreateApiClient200Response interface.
 */
export function instanceOfCreateApiClient200Response(value: object): value is CreateApiClient200Response {
    return true;
}

export function CreateApiClient200ResponseFromJSON(json: any): CreateApiClient200Response {
    return CreateApiClient200ResponseFromJSONTyped(json, false);
}

export function CreateApiClient200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiClient200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'secretKey': json['secretKey'] == null ? undefined : json['secretKey'],
    };
}

  export function CreateApiClient200ResponseToJSON(json: any): CreateApiClient200Response {
      return CreateApiClient200ResponseToJSONTyped(json, false);
  }

  export function CreateApiClient200ResponseToJSONTyped(value?: CreateApiClient200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secretKey': value['secretKey'],
    };
}

