/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetOAuth2AuthorizationParametersRequest,
  OAuth2AuthorizationParameters,
  OAuth2Properties,
} from '../models/index';
import {
    GetOAuth2AuthorizationParametersRequestFromJSON,
    GetOAuth2AuthorizationParametersRequestToJSON,
    OAuth2AuthorizationParametersFromJSON,
    OAuth2AuthorizationParametersToJSON,
    OAuth2PropertiesFromJSON,
    OAuth2PropertiesToJSON,
} from '../models/index';

export interface GetOAuth2AuthorizationParametersOperationRequest {
    getOAuth2AuthorizationParametersRequest: GetOAuth2AuthorizationParametersRequest;
}

/**
 * 
 */
export class Oauth2Api extends runtime.BaseAPI {

    /**
     * Creates request options for getOAuth2AuthorizationParameters without sending the request
     */
    async getOAuth2AuthorizationParametersRequestOpts(requestParameters: GetOAuth2AuthorizationParametersOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['getOAuth2AuthorizationParametersRequest'] == null) {
            throw new runtime.RequiredError(
                'getOAuth2AuthorizationParametersRequest',
                'Required parameter "getOAuth2AuthorizationParametersRequest" was null or undefined when calling getOAuth2AuthorizationParameters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/oauth2/authorization-parameters`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetOAuth2AuthorizationParametersRequestToJSON(requestParameters['getOAuth2AuthorizationParametersRequest']),
        };
    }

    /**
     * Retrieves oauth2 authorization parameters.
     * Retrieves oauth2 authorization parameters
     */
    async getOAuth2AuthorizationParametersRaw(requestParameters: GetOAuth2AuthorizationParametersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuth2AuthorizationParameters>> {
        const requestOptions = await this.getOAuth2AuthorizationParametersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuth2AuthorizationParametersFromJSON(jsonValue));
    }

    /**
     * Retrieves oauth2 authorization parameters.
     * Retrieves oauth2 authorization parameters
     */
    async getOAuth2AuthorizationParameters(requestParameters: GetOAuth2AuthorizationParametersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuth2AuthorizationParameters> {
        const response = await this.getOAuth2AuthorizationParametersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOAuth2Properties without sending the request
     */
    async getOAuth2PropertiesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/properties`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get OAuth2 properties.
     * Get OAuth2 properties
     */
    async getOAuth2PropertiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OAuth2Properties>> {
        const requestOptions = await this.getOAuth2PropertiesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OAuth2PropertiesFromJSON(jsonValue));
    }

    /**
     * Get OAuth2 properties.
     * Get OAuth2 properties
     */
    async getOAuth2Properties(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OAuth2Properties> {
        const response = await this.getOAuth2PropertiesRaw(initOverrides);
        return await response.value();
    }

}
