/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PropertyModel,
} from '../models/index';
import {
    PropertyModelFromJSON,
    PropertyModelToJSON,
} from '../models/index';

export interface GetWorkflowNodeDynamicPropertiesRequest {
    id: string;
    workflowNodeName: string;
    propertyName: string;
    lookupDependsOnPaths?: Array<string>;
}

/**
 * 
 */
export class WorkflowNodeDynamicPropertiesApi extends runtime.BaseAPI {

    /**
     * Get dynamic properties for an action or trigger property shown in the editor.
     * Get dynamic properties for an action or trigger property shown in the editor
     */
    async getWorkflowNodeDynamicPropertiesRaw(requestParameters: GetWorkflowNodeDynamicPropertiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PropertyModel>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkflowNodeDynamicProperties().'
            );
        }

        if (requestParameters['workflowNodeName'] == null) {
            throw new runtime.RequiredError(
                'workflowNodeName',
                'Required parameter "workflowNodeName" was null or undefined when calling getWorkflowNodeDynamicProperties().'
            );
        }

        if (requestParameters['propertyName'] == null) {
            throw new runtime.RequiredError(
                'propertyName',
                'Required parameter "propertyName" was null or undefined when calling getWorkflowNodeDynamicProperties().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lookupDependsOnPaths'] != null) {
            queryParameters['lookupDependsOnPaths'] = requestParameters['lookupDependsOnPaths'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/workflows/{id}/dynamic-properties/{workflowNodeName}/properties/{propertyName}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"workflowNodeName"}}`, encodeURIComponent(String(requestParameters['workflowNodeName']))).replace(`{${"propertyName"}}`, encodeURIComponent(String(requestParameters['propertyName']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PropertyModelFromJSON));
    }

    /**
     * Get dynamic properties for an action or trigger property shown in the editor.
     * Get dynamic properties for an action or trigger property shown in the editor
     */
    async getWorkflowNodeDynamicProperties(requestParameters: GetWorkflowNodeDynamicPropertiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PropertyModel>> {
        const response = await this.getWorkflowNodeDynamicPropertiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
