/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Public V1 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComponentInputOptionsRequest
 */
export interface ComponentInputOptionsRequest {
    /**
     * The component the input group belongs to.
     * @type {string}
     * @memberof ComponentInputOptionsRequest
     */
    componentName: string;
    /**
     * The component version.
     * @type {number}
     * @memberof ComponentInputOptionsRequest
     */
    componentVersion: number;
    /**
     * The component input group the property belongs to.
     * @type {string}
     * @memberof ComponentInputOptionsRequest
     */
    groupName: string;
    /**
     * The group member property whose options to resolve.
     * @type {string}
     * @memberof ComponentInputOptionsRequest
     */
    propertyName: string;
    /**
     * Current values of the properties this lookup depends on.
     * @type {{ [key: string]: any; }}
     * @memberof ComponentInputOptionsRequest
     */
    lookupDependsOnValues?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ComponentInputOptionsRequest
     */
    searchText?: string;
}

/**
 * Check if a given object implements the ComponentInputOptionsRequest interface.
 */
export function instanceOfComponentInputOptionsRequest(value: object): value is ComponentInputOptionsRequest {
    if (!('componentName' in value) || value['componentName'] === undefined) return false;
    if (!('componentVersion' in value) || value['componentVersion'] === undefined) return false;
    if (!('groupName' in value) || value['groupName'] === undefined) return false;
    if (!('propertyName' in value) || value['propertyName'] === undefined) return false;
    return true;
}

export function ComponentInputOptionsRequestFromJSON(json: any): ComponentInputOptionsRequest {
    return ComponentInputOptionsRequestFromJSONTyped(json, false);
}

export function ComponentInputOptionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComponentInputOptionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'componentName': json['componentName'],
        'componentVersion': json['componentVersion'],
        'groupName': json['groupName'],
        'propertyName': json['propertyName'],
        'lookupDependsOnValues': json['lookupDependsOnValues'] == null ? undefined : json['lookupDependsOnValues'],
        'searchText': json['searchText'] == null ? undefined : json['searchText'],
    };
}

export function ComponentInputOptionsRequestToJSON(json: any): ComponentInputOptionsRequest {
    return ComponentInputOptionsRequestToJSONTyped(json, false);
}

export function ComponentInputOptionsRequestToJSONTyped(value?: ComponentInputOptionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'componentName': value['componentName'],
        'componentVersion': value['componentVersion'],
        'groupName': value['groupName'],
        'propertyName': value['propertyName'],
        'lookupDependsOnValues': value['lookupDependsOnValues'],
        'searchText': value['searchText'],
    };
}

