/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded User Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSigningKey200ResponseModel
 */
export interface CreateSigningKey200ResponseModel {
    /**
     * The private key.
     * @type {string}
     * @memberof CreateSigningKey200ResponseModel
     */
    privateKey?: string;
}

/**
 * Check if a given object implements the CreateSigningKey200ResponseModel interface.
 */
export function instanceOfCreateSigningKey200ResponseModel(value: object): boolean {
    return true;
}

export function CreateSigningKey200ResponseModelFromJSON(json: any): CreateSigningKey200ResponseModel {
    return CreateSigningKey200ResponseModelFromJSONTyped(json, false);
}

export function CreateSigningKey200ResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSigningKey200ResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'privateKey': json['privateKey'] == null ? undefined : json['privateKey'],
    };
}

export function CreateSigningKey200ResponseModelToJSON(value?: CreateSigningKey200ResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'privateKey': value['privateKey'],
    };
}

