/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded User Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSigningKey200Response
 */
export interface CreateSigningKey200Response {
    /**
     * The private key.
     * @type {string}
     * @memberof CreateSigningKey200Response
     */
    privateKey?: string;
}

/**
 * Check if a given object implements the CreateSigningKey200Response interface.
 */
export function instanceOfCreateSigningKey200Response(value: object): value is CreateSigningKey200Response {
    return true;
}

export function CreateSigningKey200ResponseFromJSON(json: any): CreateSigningKey200Response {
    return CreateSigningKey200ResponseFromJSONTyped(json, false);
}

export function CreateSigningKey200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSigningKey200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'privateKey': json['privateKey'] == null ? undefined : json['privateKey'],
    };
}

  export function CreateSigningKey200ResponseToJSON(json: any): CreateSigningKey200Response {
      return CreateSigningKey200ResponseToJSONTyped(json, false);
  }

  export function CreateSigningKey200ResponseToJSONTyped(value?: CreateSigningKey200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'privateKey': value['privateKey'],
    };
}

