logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7555

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/bytechef
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
  devtools:
    livereload:
      port: 35732
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
