logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7555

spring:
  devtools:
    livereload:
      port: 35732
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true

#####

bytechef:
  datasource:
    url: jdbc:postgresql://localhost:5432/bytechef_scheduler
    username: postgres
    password: postgres
