/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Billing Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A billing subscription.
 * @export
 * @interface BillingSubscription
 */
export interface BillingSubscription {
    /**
     * The plan name.
     * @type {string}
     * @memberof BillingSubscription
     */
    planName?: string;
    /**
     * The subscription status.
     * @type {string}
     * @memberof BillingSubscription
     */
    status?: string;
    /**
     * The task limit.
     * @type {number}
     * @memberof BillingSubscription
     */
    taskLimit?: number;
    /**
     * The current period end date.
     * @type {Date}
     * @memberof BillingSubscription
     */
    currentPeriodEnd?: Date;
    /**
     * Whether the subscription cancels at period end.
     * @type {boolean}
     * @memberof BillingSubscription
     */
    cancelAtPeriodEnd?: boolean;
    /**
     * The plan name scheduled to take effect at the next billing period (set when a downgrade is pending).
     * @type {string}
     * @memberof BillingSubscription
     */
    scheduledPlanName?: string;
    /**
     * Number of task executions used in the current billing period.
     * @type {number}
     * @memberof BillingSubscription
     */
    tasksUsed?: number;
}

/**
 * Check if a given object implements the BillingSubscription interface.
 */
export function instanceOfBillingSubscription(value: object): value is BillingSubscription {
    return true;
}

export function BillingSubscriptionFromJSON(json: any): BillingSubscription {
    return BillingSubscriptionFromJSONTyped(json, false);
}

export function BillingSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'planName': json['planName'] == null ? undefined : json['planName'],
        'status': json['status'] == null ? undefined : json['status'],
        'taskLimit': json['taskLimit'] == null ? undefined : json['taskLimit'],
        'currentPeriodEnd': json['currentPeriodEnd'] == null ? undefined : (new Date(json['currentPeriodEnd'])),
        'cancelAtPeriodEnd': json['cancelAtPeriodEnd'] == null ? undefined : json['cancelAtPeriodEnd'],
        'scheduledPlanName': json['scheduledPlanName'] == null ? undefined : json['scheduledPlanName'],
        'tasksUsed': json['tasksUsed'] == null ? undefined : json['tasksUsed'],
    };
}

export function BillingSubscriptionToJSON(json: any): BillingSubscription {
    return BillingSubscriptionToJSONTyped(json, false);
}

export function BillingSubscriptionToJSONTyped(value?: BillingSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'planName': value['planName'],
        'status': value['status'],
        'taskLimit': value['taskLimit'],
        'currentPeriodEnd': value['currentPeriodEnd'] == null ? value['currentPeriodEnd'] : value['currentPeriodEnd'].toISOString(),
        'cancelAtPeriodEnd': value['cancelAtPeriodEnd'],
        'scheduledPlanName': value['scheduledPlanName'],
        'tasksUsed': value['tasksUsed'],
    };
}

