group = "com.bytechef.server"
description = "ByteChef server app"
version = properties["bytechefVersion"].toString()

springBoot {
    mainClass.set("com.bytechef.server.ServerApplication")
}

dependencies {
    implementation("io.awspring.cloud:spring-cloud-aws-starter-s3")
    implementation("io.awspring.cloud:spring-cloud-aws-starter-sqs")
    implementation(libs.org.springdoc.springdoc.openapi.starter.common)
    implementation(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    implementation("org.springframework.ai:spring-ai-starter-mcp-client")
    implementation("org.springframework.ai:spring-ai-starter-model-anthropic")
    implementation("org.springframework.ai:spring-ai-starter-model-openai")
    implementation("org.springframework.ai:spring-ai-starter-vector-store-pgvector")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-amqp")
    implementation("org.springframework.boot:spring-boot-starter-aspectj")
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("org.springframework.boot:spring-boot-starter-batch")
    implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-jackson")
    implementation("org.springframework.boot:spring-boot-starter-jms")
    implementation("org.springframework.boot:spring-boot-starter-kafka")
    implementation("org.springframework.boot:spring-boot-starter-liquibase")
    implementation("org.springframework.boot:spring-boot-starter-graphql")
    implementation("org.springframework.boot:spring-boot-starter-quartz")
    implementation("org.springframework.boot:spring-boot-starter-mail")
    implementation("org.springframework.boot:spring-boot-starter-opentelemetry")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation(project(":server:libs:ai:mcp:mcp-server"))
    implementation(project(":server:libs:ai:mcp:mcp-server-configuration:mcp-server-configuration-graphql"))
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-config"))
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-converter"))
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-repository:atlas-configuration-repository-git"))
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-repository:atlas-configuration-repository-jdbc"))
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-service"))
    implementation(project(":server:libs:atlas:atlas-coordinator:atlas-coordinator-config"))
    implementation(project(":server:libs:atlas:atlas-execution:atlas-execution-repository:atlas-execution-repository-jdbc"))
    implementation(project(":server:libs:atlas:atlas-execution:atlas-execution-config"))
    implementation(project(":server:libs:atlas:atlas-execution:atlas-execution-service"))
    implementation(project(":server:libs:atlas:atlas-file-storage:atlas-file-storage-impl"))
    implementation(project(":server:libs:atlas:atlas-worker:atlas-worker-config"))
    implementation(project(":server:libs:automation:automation-ai:automation-ai-mcp-server"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-graphql"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-instance-impl"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-rest:automation-configuration-rest-impl"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-service"))
    implementation(project(":server:libs:automation:automation-data-table:automation-data-table-graphql"))
    implementation(project(":server:libs:automation:automation-data-table:automation-data-table-service"))
    implementation(project(":server:libs:automation:automation-execution:automation-execution-service"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-file-storage:automation-knowledge-base-file-storage-impl"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-graphql"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-rest"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-service"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-worker"))
    implementation(project(":server:libs:automation:automation-mcp:automation-mcp-graphql"))
    implementation(project(":server:libs:automation:automation-mcp:automation-mcp-service"))
    implementation(project(":server:libs:automation:automation-search:automation-search-graphql"))
    implementation(project(":server:libs:automation:automation-search:automation-search-service"))
    implementation(project(":server:libs:automation:automation-swagger"))
    implementation(project(":server:libs:automation:automation-workflow:automation-workflow-coordinator"))
    implementation(project(":server:libs:automation:automation-workflow:automation-workflow-execution:automation-workflow-execution-rest"))
    implementation(project(":server:libs:automation:automation-workflow:automation-workflow-execution:automation-workflow-execution-service"))
    implementation(project(":server:libs:config:app-config"))
    implementation(project(":server:libs:config:async-config"))
    implementation(project(":server:libs:config:automation-demo-config"))
    implementation(project(":server:libs:config:cache-config"))
    implementation(project(":server:libs:config:environment-config"))
    implementation(project(":server:libs:config:jackson-config"))
    implementation(project(":server:libs:config:jdbc-config"))
    implementation(project(":server:libs:config:liquibase-config"))
    implementation(project(":server:libs:config:logback-config"))
    implementation(project(":server:libs:config:messages-config"))
    implementation(project(":server:libs:config:security-config"))
    implementation(project(":server:libs:config:static-resources-config"))
    implementation(project(":server:libs:config:tenant-single-security-config"))
    implementation(project(":server:libs:core:commons:commons-data"))
    implementation(project(":server:libs:core:encryption:encryption-filesystem"))
    implementation(project(":server:libs:core:evaluator:evaluator-impl"))
    implementation(project(":server:libs:core:encryption:encryption-impl"))
    implementation(project(":server:libs:core:encryption:encryption-property"))
    implementation(project(":server:libs:core:file-storage:file-storage-base64-service"))
    implementation(project(":server:libs:core:file-storage:file-storage-filesystem-service"))
    implementation(project(":server:libs:core:message:message-broker:message-broker-amqp"))
    implementation(project(":server:libs:core:message:message-broker:message-broker-jms"))
    implementation(project(":server:libs:core:message:message-broker:message-broker-kafka"))
    implementation(project(":server:libs:core:message:message-broker:message-broker-redis"))
    implementation(project(":server:libs:core:message:message-event:message-event-impl"))
    implementation(project(":server:libs:core:rest:rest-impl"))
    implementation(project(":server:libs:core:tenant:tenant-api"))
    implementation(project(":server:libs:core:tenant:tenant-single-service"))
    implementation(project(":server:libs:platform:platform-category:platform-category-service"))
    implementation(project(":server:libs:platform:platform-component:platform-component-context:platform-component-context-service"))
    implementation(project(":server:libs:platform:platform-component:platform-component-log:platform-component-log-graphql"))
    implementation(project(":server:libs:platform:platform-component:platform-component-log:platform-component-log-service"))
    implementation(project(":server:libs:platform:platform-component:platform-component-service"))
    implementation(project(":server:libs:platform:platform-connection:platform-connection-service"))
    implementation(project(":server:libs:platform:platform-configuration:platform-configuration-graphql"))
    implementation(project(":server:libs:platform:platform-configuration:platform-configuration-rest:platform-configuration-rest-impl"))
    implementation(project(":server:libs:platform:platform-configuration:platform-configuration-service"))
    implementation(project(":server:libs:platform:platform-coordinator"))
    implementation(project(":server:libs:platform:platform-data-storage:platform-data-storage-file-storage:platform-data-storage-file-storage-service"))
    implementation(project(":server:libs:platform:platform-data-storage:platform-data-storage-jdbc:platform-data-storage-jdbc-service"))
    implementation(project(":server:libs:platform:platform-file-storage:platform-file-storage-impl"))
    implementation(project(":server:libs:platform:platform-mcp:platform-mcp-graphql"))
    implementation(project(":server:libs:platform:platform-mcp:platform-mcp-service"))
    implementation(project(":server:libs:platform:platform-notification:platform-notification-rest"))
    implementation(project(":server:libs:platform:platform-notification:platform-notification-service"))
    implementation(project(":server:libs:platform:platform-oauth2:platform-oauth2-service"))
    implementation(project(":server:libs:platform:platform-scheduler:platform-scheduler-impl"))
    implementation(project(":server:libs:platform:platform-security:platform-security-graphql"))
    implementation(project(":server:libs:platform:platform-security:platform-security-service"))
    implementation(project(":server:libs:platform:platform-swagger"))
    implementation(project(":server:libs:platform:platform-tag:platform-tag-service"))
    implementation(project(":server:libs:platform:platform-user:platform-user-rest"))
    implementation(project(":server:libs:platform:platform-user:platform-user-service"))
    implementation(project(":server:libs:platform:platform-webhook:platform-webhook-impl"))
    implementation(project(":server:libs:platform:platform-webhook:platform-webhook-rest:platform-webhook-rest-impl"))
    implementation(project(":server:libs:platform:platform-worker"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-coordinator:platform-workflow-coordinator-impl"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-task-dispatcher:platform-workflow-task-dispatcher-service"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-test:platform-workflow-test-rest"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-test:platform-workflow-test-service"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-execution:platform-workflow-execution-rest:platform-workflow-execution-rest-impl"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-execution:platform-workflow-execution-service"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-worker:platform-workflow-worker-api"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-worker:platform-workflow-worker-impl"))

    run {
        rootProject.subprojects
            .asSequence()
            .filter { it.path.startsWith(":server:libs:modules:components") }
            .filterNot { it.path in setOf(":server:libs:modules:components:example") }
            .sortedBy { it.path }
            .forEach { implementation(project(it.path)) }
    }

    implementation(project(":server:libs:modules:task-dispatchers:approval"))
    implementation(project(":server:libs:modules:task-dispatchers:branch"))
    implementation(project(":server:libs:modules:task-dispatchers:condition"))
    implementation(project(":server:libs:modules:task-dispatchers:each"))
    implementation(project(":server:libs:modules:task-dispatchers:fork-join"))
    implementation(project(":server:libs:modules:task-dispatchers:loop"))
    implementation(project(":server:libs:modules:task-dispatchers:map"))
    implementation(project(":server:libs:modules:task-dispatchers:on-error"))
    implementation(project(":server:libs:modules:task-dispatchers:parallel"))
    implementation(project(":server:libs:modules:task-dispatchers:subflow"))
    implementation(project(":server:libs:modules:task-dispatchers:terminate"))

    implementation(project(":server:ee:libs:ai:ai-copilot:ai-copilot-rest"))
    implementation(project(":server:ee:libs:ai:ai-copilot:ai-copilot-service"))
    implementation(project(":server:ee:libs:automation:automation-api-platform:automation-api-platform-configuration:automation-api-platform-configuration-rest"))
    implementation(project(":server:ee:libs:automation:automation-api-platform:automation-api-platform-configuration:automation-api-platform-configuration-service"))
    implementation(project(":server:ee:libs:automation:automation-api-platform:automation-api-platform-handler:automation-api-platform-handler-rest"))
    implementation(project(":server:ee:libs:automation:automation-configuration:automation-configuration-public-rest"))
    implementation(project(":server:ee:libs:automation:automation-configuration:automation-configuration-rest"))
    implementation(project(":server:ee:libs:automation:automation-configuration:automation-configuration-service"))
    implementation(project(":server:ee:libs:automation:automation-security-web:automation-security-web-impl"))
    implementation(project(":server:ee:libs:config:cloud-config"))
    implementation(project(":server:ee:libs:config:observability-config"))
    implementation(project(":server:ee:libs:config:tenant-multi-data-config"))
    implementation(project(":server:ee:libs:config:tenant-multi-knowledge-base-config"))
    implementation(project(":server:ee:libs:config:tenant-multi-pgvector-config"))
    implementation(project(":server:ee:libs:config:security-sso-config"))
    implementation(project(":server:ee:libs:config:tenant-multi-security-config"))
    implementation(project(":server:ee:libs:core:cloud:cloud-aws"))
    implementation(project(":server:ee:libs:core:file-storage:file-storage-aws:file-storage-aws-api"))
    implementation(project(":server:ee:libs:core:file-storage:file-storage-aws:file-storage-aws-impl"))
    implementation(project(":server:ee:libs:core:message:message-broker:message-broker-aws"))
    implementation(project(":server:ee:libs:core:tenant:tenant-multi-service"))
    implementation(project(":server:ee:libs:embedded:embedded-ai:embedded-ai-mcp-server"))
    implementation(project(":server:ee:libs:embedded:embedded-connected-user:embedded-connected-user-graphql"))
    implementation(project(":server:ee:libs:embedded:embedded-connected-user:embedded-connected-user-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-connected-user:embedded-connected-user-service"))
    implementation(project(":server:ee:libs:embedded:embedded-configuration:embedded-configuration-graphql"))
    implementation(project(":server:ee:libs:embedded:embedded-configuration:embedded-configuration-instance-impl"))
    implementation(project(":server:ee:libs:embedded:embedded-configuration:embedded-configuration-public-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-configuration:embedded-configuration-rest:embedded-configuration-rest-impl"))
    implementation(project(":server:ee:libs:embedded:embedded-configuration:embedded-configuration-service"))
    implementation(project(":server:ee:libs:embedded:embedded-execution:embedded-execution-public-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-execution:embedded-execution-service"))
    implementation(project(":server:ee:libs:embedded:embedded-security:embedded-security-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-security:embedded-security-service"))
    implementation(project(":server:ee:libs:embedded:embedded-security-web:embedded-security-web-impl"))
    implementation(project(":server:ee:libs:embedded:embedded-swagger"))
    implementation(project(":server:ee:libs:embedded:embedded-unified:embedded-unified-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-unified:embedded-unified-service"))
    implementation(project(":server:ee:libs:embedded:embedded-webhook:embedded-webhook-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-workflow:embedded-workflow-coordinator"))
    implementation(project(":server:ee:libs:embedded:embedded-workflow:embedded-workflow-execution:embedded-workflow-execution-rest"))
    implementation(project(":server:ee:libs:embedded:embedded-workflow:embedded-workflow-execution:embedded-workflow-execution-service"))
    implementation(project(":server:ee:libs:platform:platform-api-connector:platform-api-connector-configuration:platform-api-connector-configuration-graphql"))
    implementation(project(":server:ee:libs:platform:platform-api-connector:platform-api-connector-configuration:platform-api-connector-configuration-service"))
    implementation(project(":server:ee:libs:platform:platform-api-connector:platform-api-connector-file-storage:platform-api-connector-file-storage-impl"))
    implementation(project(":server:ee:libs:platform:platform-api-connector:platform-api-connector-handler"))
    implementation(project(":server:ee:libs:platform:platform-audit:platform-audit-service"))
    implementation(project(":server:ee:libs:platform:platform-code-workflow:platform-code-workflow-configuration:platform-code-workflow-configuration-service"))
    implementation(project(":server:ee:libs:platform:platform-code-workflow:platform-code-workflow-file-storage:platform-code-workflow-file-storage-impl"))
    implementation(project(":server:ee:libs:platform:platform-configuration:platform-configuration-rest"))
    implementation(project(":server:ee:libs:platform:platform-configuration:platform-configuration-service"))
    implementation(project(":server:ee:libs:platform:platform-custom-component:platform-custom-component-handler"))
    implementation(project(":server:ee:libs:platform:platform-custom-component:platform-custom-component-configuration:platform-custom-component-configuration-rest"))
    implementation(project(":server:ee:libs:platform:platform-custom-component:platform-custom-component-configuration:platform-custom-component-configuration-graphql"))
    implementation(project(":server:ee:libs:platform:platform-custom-component:platform-custom-component-configuration:platform-custom-component-configuration-service"))
    implementation(project(":server:ee:libs:platform:platform-custom-component:platform-custom-component-file-storage:platform-custom-component-file-storage-impl"))
    implementation(project(":server:ee:libs:platform:platform-scheduler:platform-scheduler-aws"))
    implementation(project(":server:ee:libs:platform:platform-scheduler:platform-scheduler-impl"))
    implementation(project(":server:ee:libs:platform:platform-security-web:platform-security-web-impl"))
    implementation(project(":server:ee:libs:platform:platform-user:platform-user-graphql"))
    implementation(project(":server:ee:libs:platform:platform-user:platform-user-scim"))

    run {
        rootProject.subprojects
            .asSequence()
            .filter { it.path.startsWith(":server:ee:libs:modules:components") }
            .sortedBy { it.path }
            .forEach { implementation(project(it.path)) }
    }

    runtimeOnly("com.h2database:h2")
    runtimeOnly("com.zaxxer:HikariCP")
    runtimeOnly("org.postgresql:postgresql")

    testImplementation(project(":server:libs:ai:mcp:mcp-tool:mcp-tool-automation-impl"))
    testImplementation(project(":server:libs:ai:mcp:mcp-tool:mcp-tool-platform"))
    testImplementation(project(":server:libs:test:test-int-support"))
    testImplementation(project(":server:libs:core:tenant:tenant-api"))
    testImplementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-api"))
    testImplementation("org.springframework.boot:spring-boot-jdbc")
    testImplementation("org.testcontainers:testcontainers")
    testImplementation("org.testcontainers:postgresql")
    testImplementation("org.testcontainers:junit-jupiter")
}

configure<com.gorylenko.GitPropertiesPluginExtension> {
    dotGitDirectory = project.rootProject.layout.projectDirectory.dir(".git")
}
