FROM gradle:8.6.0-jdk21-alpine AS build

WORKDIR /build

COPY --chown=gradle:gradle ./.git ./.git
COPY --chown=gradle:gradle ./buildSrc ./buildSrc
COPY --chown=gradle:gradle ./gradle ./gradle
COPY --chown=gradle:gradle ./server ./server
COPY --chown=gradle:gradle ./build.gradle.kts ./build.gradle.kts
COPY --chown=gradle:gradle ./gradle.properties ./gradle.properties
COPY --chown=gradle:gradle ./settings.gradle.kts ./settings.gradle.kts

WORKDIR ./

RUN gradle bootJar --no-daemon

FROM ghcr.io/graalvm/graalvm-community:21.0.2

WORKDIR /opt

COPY --from=build /build/server/apps/server-app/build/libs/*app.jar application.jar

EXPOSE 9555

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar application.jar ${0} ${@}"]
