FROM gradle:9.2.0-jdk25-alpine AS build

WORKDIR /build

COPY --chown=gradle:gradle ./.git ./.git
COPY --chown=gradle:gradle ./buildSrc ./buildSrc
COPY --chown=gradle:gradle ./gradle ./gradle
COPY --chown=gradle:gradle ./cli ./cli
COPY --chown=gradle:gradle ./sdks ./sdks
COPY --chown=gradle:gradle ./server ./server
COPY --chown=gradle:gradle ./build.gradle.kts ./build.gradle.kts
COPY --chown=gradle:gradle ./gradle.properties ./gradle.properties
COPY --chown=gradle:gradle ./settings.gradle.kts ./settings.gradle.kts

WORKDIR ./

RUN gradle bootJar --no-daemon

FROM ghcr.io/graalvm/graalvm-community:25.0.0

WORKDIR /opt

ENV JAVA_TOOL_OPTIONS="--enable-native-access=ALL-UNNAMED"

COPY --from=build /build/server/apps/server-app/build/libs/server-app*.jar server-app.jar

EXPOSE 9555

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar server-app.jar"]
