dependencies {
    implementation("com.github.ben-manes.caffeine:caffeine")
    implementation("io.awspring.cloud:spring-cloud-aws-secrets-manager")
    implementation("org.apache.commons:commons-lang3")
    implementation("org.slf4j:slf4j-api")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("software.amazon.awssdk:secretsmanager")
    implementation("tools.jackson.core:jackson-databind")
    implementation(project(":server:libs:config:app-config"))
    implementation(project(":server:libs:core:commons:commons-util"))
    implementation(project(":server:libs:core:tenant:tenant-api"))
    implementation(project(":server:libs:platform:platform-api"))
    implementation(project(":server:libs:platform:platform-credential-store:platform-credential-store-api"))
    implementation(project(":server:ee:libs:core:cloud:cloud-aws"))

    testImplementation("io.awspring.cloud:spring-cloud-aws-starter-secrets-manager")
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:localstack")
    testImplementation(project(":server:libs:config:jackson-config"))
    testImplementation(project(":server:libs:platform:platform-connection:platform-connection-api"))
    testImplementation(project(":server:libs:test:test-int-support"))
}
