label: Function Demo

inputs:
  - name: yourName
    label: Your Name
    type: string
    required: true

tasks:
  - name: JS test
    type: function/1.0/js
    context:
      randomNum : 1
      randomInput: ${yourName}
    source: >
      print("My random number " + randomNum);
      print("My random input " + randomInput);