/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Workflow Test Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatus200Response
 */
export interface GetStatus200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetStatus200Response
     */
    running?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetStatus200Response
     */
    jobId?: number;
}

/**
 * Check if a given object implements the GetStatus200Response interface.
 */
export function instanceOfGetStatus200Response(value: object): value is GetStatus200Response {
    return true;
}

export function GetStatus200ResponseFromJSON(json: any): GetStatus200Response {
    return GetStatus200ResponseFromJSONTyped(json, false);
}

export function GetStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'running': json['running'] == null ? undefined : json['running'],
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function GetStatus200ResponseToJSON(json: any): GetStatus200Response {
    return GetStatus200ResponseToJSONTyped(json, false);
}

export function GetStatus200ResponseToJSONTyped(value?: GetStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'running': value['running'],
        'jobId': value['jobId'],
    };
}

