/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Workflow Test Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobModel } from './JobModel';
import {
    JobModelFromJSON,
    JobModelFromJSONTyped,
    JobModelToJSON,
} from './JobModel';
import type { TriggerExecutionModel } from './TriggerExecutionModel';
import {
    TriggerExecutionModelFromJSON,
    TriggerExecutionModelFromJSONTyped,
    TriggerExecutionModelToJSON,
} from './TriggerExecutionModel';

/**
 * Contains information about test execution of a workflow.
 * @export
 * @interface WorkflowTestExecutionModel
 */
export interface WorkflowTestExecutionModel {
    /**
     * 
     * @type {JobModel}
     * @memberof WorkflowTestExecutionModel
     */
    job?: JobModel;
    /**
     * 
     * @type {TriggerExecutionModel}
     * @memberof WorkflowTestExecutionModel
     */
    triggerExecution?: TriggerExecutionModel;
}

/**
 * Check if a given object implements the WorkflowTestExecutionModel interface.
 */
export function instanceOfWorkflowTestExecutionModel(value: object): boolean {
    return true;
}

export function WorkflowTestExecutionModelFromJSON(json: any): WorkflowTestExecutionModel {
    return WorkflowTestExecutionModelFromJSONTyped(json, false);
}

export function WorkflowTestExecutionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowTestExecutionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'job': json['job'] == null ? undefined : JobModelFromJSON(json['job']),
        'triggerExecution': json['triggerExecution'] == null ? undefined : TriggerExecutionModelFromJSON(json['triggerExecution']),
    };
}

export function WorkflowTestExecutionModelToJSON(value?: WorkflowTestExecutionModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'job': JobModelToJSON(value['job']),
        'triggerExecution': TriggerExecutionModelToJSON(value['triggerExecution']),
    };
}

