dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework:spring-web")
    implementation("org.apache.commons:commons-lang3")
    implementation("tools.jackson.core:jackson-databind")
    implementation(project(":server:libs:core:commons:commons-util"))
    implementation(project(":server:libs:core:commons:commons-data"))
    implementation(project(":server:libs:platform:platform-mail"))
    implementation(project(":server:libs:platform:platform-notification:platform-notification-api"))

    testImplementation("org.springframework.boot:spring-boot-starter-cache-test")
    testImplementation(project(":server:libs:config:liquibase-config"))
    testImplementation(project(":server:libs:test:test-int-support"))
    testImplementation(project(":server:libs:core:commons:commons-data"))
    testImplementation(project(":server:libs:core:encryption:encryption-impl"))
    testImplementation(project(":server:libs:core:evaluator:evaluator-impl"))
    testImplementation(project(":server:libs:platform:platform-configuration:platform-configuration-api"))
    testImplementation(project(":server:libs:platform:platform-connection:platform-connection-service"))
    testImplementation(project(":server:libs:platform:platform-tag:platform-tag-service"))
}
