/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Billing Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BillingSubscription,
    BillingSubscriptionFromJSON,
    BillingSubscriptionToJSON,
} from '../models/BillingSubscription';
import {
    type CheckoutSession,
    CheckoutSessionFromJSON,
    CheckoutSessionToJSON,
} from '../models/CheckoutSession';
import {
    type CheckoutSessionRequest,
    CheckoutSessionRequestFromJSON,
    CheckoutSessionRequestToJSON,
} from '../models/CheckoutSessionRequest';

export interface CreateCheckoutSessionRequest {
    checkoutSessionRequest: CheckoutSessionRequest;
}

export interface UpgradeSubscriptionRequest {
    checkoutSessionRequest: CheckoutSessionRequest;
}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelSubscription without sending the request
     */
    async cancelSubscriptionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/billing/subscription`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel the current billing subscription at the end of the current billing period.
     * Cancel the current billing subscription at period end
     */
    async cancelSubscriptionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelSubscriptionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Cancel the current billing subscription at the end of the current billing period.
     * Cancel the current billing subscription at period end
     */
    async cancelSubscription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelSubscriptionRaw(initOverrides);
    }

    /**
     * Creates request options for createCheckoutSession without sending the request
     */
    async createCheckoutSessionRequestOpts(requestParameters: CreateCheckoutSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['checkoutSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'checkoutSessionRequest',
                'Required parameter "checkoutSessionRequest" was null or undefined when calling createCheckoutSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/billing/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckoutSessionRequestToJSON(requestParameters['checkoutSessionRequest']),
        };
    }

    /**
     * Create a Stripe Checkout Session
     * Create a Stripe Checkout Session
     */
    async createCheckoutSessionRaw(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSession>> {
        const requestOptions = await this.createCheckoutSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionFromJSON(jsonValue));
    }

    /**
     * Create a Stripe Checkout Session
     * Create a Stripe Checkout Session
     */
    async createCheckoutSession(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSession> {
        const response = await this.createCheckoutSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCurrentSubscription without sending the request
     */
    async getCurrentSubscriptionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/billing/subscription`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current billing subscription
     * Get the current billing subscription
     */
    async getCurrentSubscriptionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BillingSubscription>> {
        const requestOptions = await this.getCurrentSubscriptionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BillingSubscriptionFromJSON(jsonValue));
    }

    /**
     * Get the current billing subscription
     * Get the current billing subscription
     */
    async getCurrentSubscription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BillingSubscription> {
        const response = await this.getCurrentSubscriptionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reactivateSubscription without sending the request
     */
    async reactivateSubscriptionRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/billing/reactivate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reactivate a subscription that was scheduled for cancellation at period end.
     * Reactivate a cancelled-at-period-end billing subscription
     */
    async reactivateSubscriptionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.reactivateSubscriptionRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reactivate a subscription that was scheduled for cancellation at period end.
     * Reactivate a cancelled-at-period-end billing subscription
     */
    async reactivateSubscription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reactivateSubscriptionRaw(initOverrides);
    }

    /**
     * Creates request options for upgradeSubscription without sending the request
     */
    async upgradeSubscriptionRequestOpts(requestParameters: UpgradeSubscriptionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['checkoutSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'checkoutSessionRequest',
                'Required parameter "checkoutSessionRequest" was null or undefined when calling upgradeSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/billing/subscription`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CheckoutSessionRequestToJSON(requestParameters['checkoutSessionRequest']),
        };
    }

    /**
     * Upgrade or downgrade the current billing subscription. Upgrades are applied immediately with prorated charge; downgrades are scheduled for the end of the current billing period.
     * Upgrade or downgrade the current billing subscription
     */
    async upgradeSubscriptionRaw(requestParameters: UpgradeSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.upgradeSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upgrade or downgrade the current billing subscription. Upgrades are applied immediately with prorated charge; downgrades are scheduled for the end of the current billing period.
     * Upgrade or downgrade the current billing subscription
     */
    async upgradeSubscription(requestParameters: UpgradeSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.upgradeSubscriptionRaw(requestParameters, initOverrides);
    }

}
