/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Workflow Execution Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateJob200Response
 */
export interface CreateJob200Response {
    /**
     * The id of an executed job.
     * @type {number}
     * @memberof CreateJob200Response
     */
    jobId?: number;
}

/**
 * Check if a given object implements the CreateJob200Response interface.
 */
export function instanceOfCreateJob200Response(value: object): value is CreateJob200Response {
    return true;
}

export function CreateJob200ResponseFromJSON(json: any): CreateJob200Response {
    return CreateJob200ResponseFromJSONTyped(json, false);
}

export function CreateJob200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJob200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function CreateJob200ResponseToJSON(value?: CreateJob200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobId': value['jobId'],
    };
}

