/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WorkflowFormat } from './WorkflowFormat';
import {
    WorkflowFormatFromJSON,
    WorkflowFormatFromJSONTyped,
    WorkflowFormatToJSON,
} from './WorkflowFormat';

/**
 * 
 * @export
 * @interface PostWorkflowRequest
 */
export interface PostWorkflowRequest {
    /**
     * Definition of the workflow that is executed as a job.
     * @type {string}
     * @memberof PostWorkflowRequest
     */
    definition: string;
    /**
     * 
     * @type {WorkflowFormat}
     * @memberof PostWorkflowRequest
     */
    format: WorkflowFormat;
    /**
     * 
     * @type {string}
     * @memberof PostWorkflowRequest
     */
    sourceType?: PostWorkflowRequestSourceTypeEnum;
}


/**
 * @export
 */
export const PostWorkflowRequestSourceTypeEnum = {
    Jdbc: 'JDBC'
} as const;
export type PostWorkflowRequestSourceTypeEnum = typeof PostWorkflowRequestSourceTypeEnum[keyof typeof PostWorkflowRequestSourceTypeEnum];


/**
 * Check if a given object implements the PostWorkflowRequest interface.
 */
export function instanceOfPostWorkflowRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "definition" in value;
    isInstance = isInstance && "format" in value;

    return isInstance;
}

export function PostWorkflowRequestFromJSON(json: any): PostWorkflowRequest {
    return PostWorkflowRequestFromJSONTyped(json, false);
}

export function PostWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWorkflowRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'definition': json['definition'],
        'format': WorkflowFormatFromJSON(json['format']),
        'sourceType': !exists(json, 'sourceType') ? undefined : json['sourceType'],
    };
}

export function PostWorkflowRequestToJSON(value?: PostWorkflowRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'definition': value.definition,
        'format': WorkflowFormatToJSON(value.format),
        'sourceType': value.sourceType,
    };
}

