extend type Query {
    identityProvider(id: ID!): IdentityProviderType
    identityProviders: [IdentityProviderType]!
}

extend type Mutation {
    createIdentityProvider(input: IdentityProviderInput!): IdentityProviderType!
    deleteIdentityProvider(id: ID!): Boolean!
    updateIdentityProvider(id: ID!, input: IdentityProviderInput!): IdentityProviderType!
}

type IdentityProviderType {
    authoritiesClaim: String
    authorityMappings: [AuthorityMappingType!]!
    autoProvision: Boolean!
    clientId: String
    createdBy: String
    createdDate: Long
    defaultAuthority: String!
    domains: [String!]!
    enabled: Boolean!
    enforced: Boolean!
    id: ID!
    issuerUri: String
    lastModifiedBy: String
    lastModifiedDate: Long
    mcpEmbedded: Boolean!
    mcpAutomation: Boolean!
    mcpManagement: Boolean!
    metadataUri: String
    mfaMethod: String
    mfaRequired: Boolean!
    name: String!
    nameIdFormat: String
    scopes: String
    signingCertificate: String
    type: String!
    validateMcpAudience: Boolean!
}

type AuthorityMappingType {
    authority: String!
    externalGroup: String!
}

input IdentityProviderInput {
    authoritiesClaim: String
    authorityMappings: [AuthorityMappingInput!]
    autoProvision: Boolean
    clientId: String
    clientSecret: String
    defaultAuthority: String
    domains: [String!]!
    enabled: Boolean
    enforced: Boolean
    issuerUri: String
    mcpEmbedded: Boolean
    mcpAutomation: Boolean
    mcpManagement: Boolean
    metadataUri: String
    mfaMethod: String
    mfaRequired: Boolean
    name: String!
    nameIdFormat: String
    scopes: String
    signingCertificate: String
    type: String
    validateMcpAudience: Boolean
}

input AuthorityMappingInput {
    authority: String!
    externalGroup: String!
}
