/* tslint:disable */
/* eslint-disable */
/**
 * Core Workflow API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExecutionErrorModel } from './ExecutionErrorModel';
import {
    ExecutionErrorModelFromJSON,
    ExecutionErrorModelFromJSONTyped,
    ExecutionErrorModelToJSON,
} from './ExecutionErrorModel';
import type { WebhookModel } from './WebhookModel';
import {
    WebhookModelFromJSON,
    WebhookModelFromJSONTyped,
    WebhookModelToJSON,
} from './WebhookModel';

/**
 * Represents an execution of a workflow.
 * @export
 * @interface JobBasicModel
 */
export interface JobBasicModel {
    /**
     * The created by.
     * @type {string}
     * @memberof JobBasicModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof JobBasicModel
     */
    readonly createdDate?: Date;
    /**
     * The index of the step on the job's workflow on which the job is working on right now.
     * @type {number}
     * @memberof JobBasicModel
     */
    readonly currentTask?: number;
    /**
     * The time execution entered end status COMPLETED, STOPPED, FAILED
     * @type {Date}
     * @memberof JobBasicModel
     */
    endDate?: Date;
    /**
     * 
     * @type {ExecutionErrorModel}
     * @memberof JobBasicModel
     */
    error?: ExecutionErrorModel;
    /**
     * The id of a job.
     * @type {string}
     * @memberof JobBasicModel
     */
    readonly id?: string;
    /**
     * The key-value map of the inputs passed to the job when it was created.
     * @type {{ [key: string]: object; }}
     * @memberof JobBasicModel
     */
    readonly inputs?: { [key: string]: object; };
    /**
     * The job's human-readable name.
     * @type {string}
     * @memberof JobBasicModel
     */
    readonly label?: string;
    /**
     * The last modified by.
     * @type {string}
     * @memberof JobBasicModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof JobBasicModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The key-value map of the outputs returned.
     * @type {{ [key: string]: object; }}
     * @memberof JobBasicModel
     */
    readonly outputs?: { [key: string]: object; };
    /**
     * The id of the parent task that created this job. Required for sub-flows.
     * @type {number}
     * @memberof JobBasicModel
     */
    readonly parentTaskExecutionId?: number;
    /**
     * The priority value.
     * @type {number}
     * @memberof JobBasicModel
     */
    readonly priority: number;
    /**
     * The time of when the job began.
     * @type {Date}
     * @memberof JobBasicModel
     */
    readonly startDate: Date;
    /**
     * The job's status.
     * @type {string}
     * @memberof JobBasicModel
     */
    readonly status: JobBasicModelStatusEnum;
    /**
     * The list of the webhooks configured.
     * @type {Array<WebhookModel>}
     * @memberof JobBasicModel
     */
    readonly webhooks?: Array<WebhookModel>;
    /**
     * 
     * @type {string}
     * @memberof JobBasicModel
     */
    readonly workflowId?: string;
}


/**
 * @export
 */
export const JobBasicModelStatusEnum = {
    Created: 'CREATED',
    Started: 'STARTED',
    Stopped: 'STOPPED',
    Failed: 'FAILED',
    Completed: 'COMPLETED'
} as const;
export type JobBasicModelStatusEnum = typeof JobBasicModelStatusEnum[keyof typeof JobBasicModelStatusEnum];


/**
 * Check if a given object implements the JobBasicModel interface.
 */
export function instanceOfJobBasicModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "priority" in value;
    isInstance = isInstance && "startDate" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function JobBasicModelFromJSON(json: any): JobBasicModel {
    return JobBasicModelFromJSONTyped(json, false);
}

export function JobBasicModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobBasicModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'currentTask': !exists(json, 'currentTask') ? undefined : json['currentTask'],
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'error': !exists(json, 'error') ? undefined : ExecutionErrorModelFromJSON(json['error']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'inputs': !exists(json, 'inputs') ? undefined : json['inputs'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'lastModifiedBy': !exists(json, 'lastModifiedBy') ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : (new Date(json['lastModifiedDate'])),
        'outputs': !exists(json, 'outputs') ? undefined : json['outputs'],
        'parentTaskExecutionId': !exists(json, 'parentTaskExecutionId') ? undefined : json['parentTaskExecutionId'],
        'priority': json['priority'],
        'startDate': (new Date(json['startDate'])),
        'status': json['status'],
        'webhooks': !exists(json, 'webhooks') ? undefined : ((json['webhooks'] as Array<any>).map(WebhookModelFromJSON)),
        'workflowId': !exists(json, 'workflowId') ? undefined : json['workflowId'],
    };
}

export function JobBasicModelToJSON(value?: JobBasicModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'error': ExecutionErrorModelToJSON(value.error),
    };
}

