/* tslint:disable */
/* eslint-disable */
/**
 * The Automation Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TriggerFormInput } from './TriggerFormInput';
import {
    TriggerFormInputFromJSON,
    TriggerFormInputFromJSONTyped,
    TriggerFormInputToJSON,
    TriggerFormInputToJSONTyped,
} from './TriggerFormInput';

/**
 * 
 * @export
 * @interface ApproveForm
 */
export interface ApproveForm {
    /**
     * 
     * @type {string}
     * @memberof ApproveForm
     */
    formDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ApproveForm
     */
    formTitle?: string;
    /**
     * 
     * @type {Array<TriggerFormInput>}
     * @memberof ApproveForm
     */
    inputs?: Array<TriggerFormInput>;
}

/**
 * Check if a given object implements the ApproveForm interface.
 */
export function instanceOfApproveForm(value: object): value is ApproveForm {
    return true;
}

export function ApproveFormFromJSON(json: any): ApproveForm {
    return ApproveFormFromJSONTyped(json, false);
}

export function ApproveFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveForm {
    if (json == null) {
        return json;
    }
    return {
        
        'formDescription': json['formDescription'] == null ? undefined : json['formDescription'],
        'formTitle': json['formTitle'] == null ? undefined : json['formTitle'],
        'inputs': json['inputs'] == null ? undefined : ((json['inputs'] as Array<any>).map(TriggerFormInputFromJSON)),
    };
}

export function ApproveFormToJSON(json: any): ApproveForm {
    return ApproveFormToJSONTyped(json, false);
}

export function ApproveFormToJSONTyped(value?: ApproveForm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formDescription': value['formDescription'],
        'formTitle': value['formTitle'],
        'inputs': value['inputs'] == null ? undefined : ((value['inputs'] as Array<any>).map(TriggerFormInputToJSON)),
    };
}

