/* tslint:disable */
/* eslint-disable */
/**
 * The Automation Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComponentInputReference } from './ComponentInputReference';
import {
    ComponentInputReferenceFromJSON,
    ComponentInputReferenceFromJSONTyped,
    ComponentInputReferenceToJSON,
    ComponentInputReferenceToJSONTyped,
} from './ComponentInputReference';

/**
 * 
 * @export
 * @interface WorkflowInput
 */
export interface WorkflowInput {
    /**
     * If true, the input is configured in the admin integration instance configuration; if false (default), it is rendered in the end-user connect dialog.
     * @type {boolean}
     * @memberof WorkflowInput
     */
    internalOnly?: boolean;
    /**
     * The descriptive name of an input
     * @type {string}
     * @memberof WorkflowInput
     */
    label?: string;
    /**
     * The name of an input
     * @type {string}
     * @memberof WorkflowInput
     */
    name: string;
    /**
     * For field_mapping inputs, the name of the object whose fields are being mapped.
     * @type {string}
     * @memberof WorkflowInput
     */
    objectName?: string;
    /**
     * If an input is required, or not
     * @type {boolean}
     * @memberof WorkflowInput
     */
    required?: boolean;
    /**
     * The type of an input, for example \"string\"
     * @type {string}
     * @memberof WorkflowInput
     */
    type?: string;
    /**
     * 
     * @type {ComponentInputReference}
     * @memberof WorkflowInput
     */
    componentReference?: ComponentInputReference;
}

/**
 * Check if a given object implements the WorkflowInput interface.
 */
export function instanceOfWorkflowInput(value: object): value is WorkflowInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WorkflowInputFromJSON(json: any): WorkflowInput {
    return WorkflowInputFromJSONTyped(json, false);
}

export function WorkflowInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowInput {
    if (json == null) {
        return json;
    }
    return {
        
        'internalOnly': json['internalOnly'] == null ? undefined : json['internalOnly'],
        'label': json['label'] == null ? undefined : json['label'],
        'name': json['name'],
        'objectName': json['objectName'] == null ? undefined : json['objectName'],
        'required': json['required'] == null ? undefined : json['required'],
        'type': json['type'] == null ? undefined : json['type'],
        'componentReference': json['componentReference'] == null ? undefined : ComponentInputReferenceFromJSON(json['componentReference']),
    };
}

export function WorkflowInputToJSON(json: any): WorkflowInput {
    return WorkflowInputToJSONTyped(json, false);
}

export function WorkflowInputToJSONTyped(value?: WorkflowInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'internalOnly': value['internalOnly'],
        'label': value['label'],
        'name': value['name'],
        'objectName': value['objectName'],
        'required': value['required'],
        'type': value['type'],
        'componentReference': ComponentInputReferenceToJSON(value['componentReference']),
    };
}

