/* tslint:disable */
/* eslint-disable */
/**
 * Embedded Execution API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of an integration.
 * @export
 */
export const IntegrationStatusModel = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED'
} as const;
export type IntegrationStatusModel = typeof IntegrationStatusModel[keyof typeof IntegrationStatusModel];


export function instanceOfIntegrationStatusModel(value: any): boolean {
    return Object.values(IntegrationStatusModel).includes(value);
}

export function IntegrationStatusModelFromJSON(json: any): IntegrationStatusModel {
    return IntegrationStatusModelFromJSONTyped(json, false);
}

export function IntegrationStatusModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationStatusModel {
    return json as IntegrationStatusModel;
}

export function IntegrationStatusModelToJSON(value?: IntegrationStatusModel | null): any {
    return value as any;
}

