apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    editable: false
    jsonData:
      httpMethod: POST
#        exemplarTraceIdDestinations:
#          - name: trace_id
#            datasourceUid: tempo
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://host.docker.internal:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      maxLines: 50
#      derivedFields:
#        - datasourceUid: tempo
#          matcherRegex: '.+ --- \[.+\] \[.+\] \[(\w*)-\w*\] .+'
#          name: TraceID
#          url: $${__value.raw}
