apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://host.docker.internal:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: Prometheus
      tracesToLogs:
        datasourceUid: loki
        mapTagNamesEnabled: true
        filterByTraceID: true
        filterBySpanID: true
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
      lokiSearch:
        datasourceUid: loki
      serviceMap:
        datasourceUid: Prometheus
      nodeGraph:
        enabled: true
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://host.docker.internal:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      maxLines: 50
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '.+ --- \[.+\] \[.+\] \[(\w*)-\w*\] .+'
          name: TraceID
          url: $${__value.raw}
