export const VALUE_PROPERTY_CONTROL_TYPES = {
    ARRAY: 'ARRAY_BUILDER',
    BOOLEAN: 'SELECT',
    DATE: 'DATE',
    DATE_TIME: 'DATE_TIME',
    FILE_ENTRY: 'FILE_ENTRY',
    INTEGER: 'INTEGER',
    NULL: 'NULL',
    NUMBER: 'NUMBER',
    OBJECT: 'OBJECT_BUILDER',
    STRING: 'TEXT',
    TIME: 'TIME',
};
