server:
  port: 7777

spring:
  devtools:
    livereload:
      port: 35734

#####

bytechef:
  datasource:
    url: jdbc:postgresql://localhost:5432/bytechef_execution
    username: postgres
    password: postgres
