management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${bytechef.datasource.url}
    username: ${bytechef.datasource.username}
    password: ${bytechef.datasource.password}
    hikari:
      poolName: Hikari
  liquibase:
      contexts: execution,data-storage
  task:
    execution:
      thread-name-prefix: execution-service-app-task-
