server:
  port: 7555

spring:
  devtools:
    livereload:
      port: 35732

#####

bytechef:
  datasource:
    url: jdbc:postgresql://localhost:5432/bytechef_scheduler
    username: postgres
    password: postgres
