spring:
  application:
    name: configuration-service-app
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server-service-app
  config:
    import: optional:configserver:http://localhost:6111
  profiles:
    active: #spring.profiles.active#
