/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisplayOption } from './DisplayOption';
import {
    DisplayOptionFromJSON,
    DisplayOptionFromJSONTyped,
    DisplayOptionToJSON,
} from './DisplayOption';
import type { PropertyType } from './PropertyType';
import {
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './PropertyType';

/**
 * 
 * @export
 * @interface BooleanProperty
 */
export interface BooleanProperty {
    /**
     * 
     * @type {string}
     * @memberof BooleanProperty
     */
    description?: string;
    /**
     * 
     * @type {DisplayOption}
     * @memberof BooleanProperty
     */
    displayOption?: DisplayOption;
    /**
     * 
     * @type {string}
     * @memberof BooleanProperty
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof BooleanProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BooleanProperty
     */
    placeholder?: string;
    /**
     * 
     * @type {PropertyType}
     * @memberof BooleanProperty
     */
    type?: PropertyType;
}

/**
 * Check if a given object implements the BooleanProperty interface.
 */
export function instanceOfBooleanProperty(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BooleanPropertyFromJSON(json: any): BooleanProperty {
    return BooleanPropertyFromJSONTyped(json, false);
}

export function BooleanPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'displayOption': !exists(json, 'displayOption') ? undefined : DisplayOptionFromJSON(json['displayOption']),
        'label': !exists(json, 'label') ? undefined : json['label'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'placeholder': !exists(json, 'placeholder') ? undefined : json['placeholder'],
        'type': !exists(json, 'type') ? undefined : PropertyTypeFromJSON(json['type']),
    };
}

export function BooleanPropertyToJSON(value?: BooleanProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'displayOption': DisplayOptionToJSON(value.displayOption),
        'label': value.label,
        'name': value.name,
        'placeholder': value.placeholder,
        'type': PropertyTypeToJSON(value.type),
    };
}

