/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Contains configurations and connections required for the execution of integration workflows for a connected user.
 * @export
 * @interface IntegrationInstanceBasicModel
 */
export interface IntegrationInstanceBasicModel {
    /**
     * The id of a connection.
     * @type {number}
     * @memberof IntegrationInstanceBasicModel
     */
    connectionId: number;
    /**
     * The created by.
     * @type {string}
     * @memberof IntegrationInstanceBasicModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof IntegrationInstanceBasicModel
     */
    readonly createdDate?: Date;
    /**
     * The id of an integration instance.
     * @type {number}
     * @memberof IntegrationInstanceBasicModel
     */
    readonly id?: number;
    /**
     * The last execution date.
     * @type {Date}
     * @memberof IntegrationInstanceBasicModel
     */
    readonly lastExecutionDate?: Date;
    /**
     * The last modified by.
     * @type {string}
     * @memberof IntegrationInstanceBasicModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof IntegrationInstanceBasicModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * Th id of an integration instance configuration.
     * @type {number}
     * @memberof IntegrationInstanceBasicModel
     */
    integrationInstanceConfigurationId?: number;
    /**
     * If an integration instance is enabled or not.
     * @type {boolean}
     * @memberof IntegrationInstanceBasicModel
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the IntegrationInstanceBasicModel interface.
 */
export function instanceOfIntegrationInstanceBasicModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "connectionId" in value;

    return isInstance;
}

export function IntegrationInstanceBasicModelFromJSON(json: any): IntegrationInstanceBasicModel {
    return IntegrationInstanceBasicModelFromJSONTyped(json, false);
}

export function IntegrationInstanceBasicModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationInstanceBasicModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastExecutionDate': !exists(json, 'lastExecutionDate') ? undefined : (new Date(json['lastExecutionDate'])),
        'lastModifiedBy': !exists(json, 'lastModifiedBy') ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : (new Date(json['lastModifiedDate'])),
        'integrationInstanceConfigurationId': !exists(json, 'integrationInstanceConfigurationId') ? undefined : json['integrationInstanceConfigurationId'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function IntegrationInstanceBasicModelToJSON(value?: IntegrationInstanceBasicModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connectionId': value.connectionId,
        'integrationInstanceConfigurationId': value.integrationInstanceConfigurationId,
        'enabled': value.enabled,
    };
}

