/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IntegrationInstanceAllOfIntegrationInstanceConfigurationModel } from './IntegrationInstanceAllOfIntegrationInstanceConfigurationModel';
import {
    IntegrationInstanceAllOfIntegrationInstanceConfigurationModelFromJSON,
    IntegrationInstanceAllOfIntegrationInstanceConfigurationModelFromJSONTyped,
    IntegrationInstanceAllOfIntegrationInstanceConfigurationModelToJSON,
} from './IntegrationInstanceAllOfIntegrationInstanceConfigurationModel';

/**
 * Contains configurations and connections required for the execution of integration workflows for a connected user.
 * @export
 * @interface IntegrationInstanceModel
 */
export interface IntegrationInstanceModel {
    /**
     * The id of a connection.
     * @type {number}
     * @memberof IntegrationInstanceModel
     */
    connectionId: number;
    /**
     * The created by.
     * @type {string}
     * @memberof IntegrationInstanceModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof IntegrationInstanceModel
     */
    readonly createdDate?: Date;
    /**
     * The id of an integration instance.
     * @type {number}
     * @memberof IntegrationInstanceModel
     */
    readonly id?: number;
    /**
     * The last execution date.
     * @type {Date}
     * @memberof IntegrationInstanceModel
     */
    readonly lastExecutionDate?: Date;
    /**
     * The last modified by.
     * @type {string}
     * @memberof IntegrationInstanceModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof IntegrationInstanceModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * Th id of an integration instance configuration.
     * @type {number}
     * @memberof IntegrationInstanceModel
     */
    integrationInstanceConfigurationId?: number;
    /**
     * If an integration instance is enabled or not.
     * @type {boolean}
     * @memberof IntegrationInstanceModel
     */
    enabled?: boolean;
    /**
     * 
     * @type {IntegrationInstanceAllOfIntegrationInstanceConfigurationModel}
     * @memberof IntegrationInstanceModel
     */
    integrationInstanceConfiguration?: IntegrationInstanceAllOfIntegrationInstanceConfigurationModel;
    /**
     * 
     * @type {number}
     * @memberof IntegrationInstanceModel
     */
    version?: number;
}

/**
 * Check if a given object implements the IntegrationInstanceModel interface.
 */
export function instanceOfIntegrationInstanceModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "connectionId" in value;

    return isInstance;
}

export function IntegrationInstanceModelFromJSON(json: any): IntegrationInstanceModel {
    return IntegrationInstanceModelFromJSONTyped(json, false);
}

export function IntegrationInstanceModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationInstanceModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lastExecutionDate': !exists(json, 'lastExecutionDate') ? undefined : (new Date(json['lastExecutionDate'])),
        'lastModifiedBy': !exists(json, 'lastModifiedBy') ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': !exists(json, 'lastModifiedDate') ? undefined : (new Date(json['lastModifiedDate'])),
        'integrationInstanceConfigurationId': !exists(json, 'integrationInstanceConfigurationId') ? undefined : json['integrationInstanceConfigurationId'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'integrationInstanceConfiguration': !exists(json, 'integrationInstanceConfiguration') ? undefined : IntegrationInstanceAllOfIntegrationInstanceConfigurationModelFromJSON(json['integrationInstanceConfiguration']),
        'version': !exists(json, '__version') ? undefined : json['__version'],
    };
}

export function IntegrationInstanceModelToJSON(value?: IntegrationInstanceModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connectionId': value.connectionId,
        'integrationInstanceConfigurationId': value.integrationInstanceConfigurationId,
        'enabled': value.enabled,
        'integrationInstanceConfiguration': IntegrationInstanceAllOfIntegrationInstanceConfigurationModelToJSON(value.integrationInstanceConfiguration),
        '__version': value.version,
    };
}

