/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkflowNodeParameterDisplayConditions200ResponseModel
 */
export interface GetWorkflowNodeParameterDisplayConditions200ResponseModel {
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof GetWorkflowNodeParameterDisplayConditions200ResponseModel
     */
    displayConditions?: { [key: string]: boolean; };
}

/**
 * Check if a given object implements the GetWorkflowNodeParameterDisplayConditions200ResponseModel interface.
 */
export function instanceOfGetWorkflowNodeParameterDisplayConditions200ResponseModel(value: object): boolean {
    return true;
}

export function GetWorkflowNodeParameterDisplayConditions200ResponseModelFromJSON(json: any): GetWorkflowNodeParameterDisplayConditions200ResponseModel {
    return GetWorkflowNodeParameterDisplayConditions200ResponseModelFromJSONTyped(json, false);
}

export function GetWorkflowNodeParameterDisplayConditions200ResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkflowNodeParameterDisplayConditions200ResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'displayConditions': json['displayConditions'] == null ? undefined : json['displayConditions'],
    };
}

export function GetWorkflowNodeParameterDisplayConditions200ResponseModelToJSON(value?: GetWorkflowNodeParameterDisplayConditions200ResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayConditions': value['displayConditions'],
    };
}

