/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HelpModel } from './HelpModel';
import {
    HelpModelFromJSON,
    HelpModelFromJSONTyped,
    HelpModelToJSON,
} from './HelpModel';
import type { TriggerTypeModel } from './TriggerTypeModel';
import {
    TriggerTypeModelFromJSON,
    TriggerTypeModelFromJSONTyped,
    TriggerTypeModelToJSON,
} from './TriggerTypeModel';

/**
 * A trigger definition defines ways to trigger workflows from the outside services.
 * @export
 * @interface TriggerDefinitionBasicModel
 */
export interface TriggerDefinitionBasicModel {
    /**
     * The description.
     * @type {string}
     * @memberof TriggerDefinitionBasicModel
     */
    description?: string;
    /**
     * 
     * @type {HelpModel}
     * @memberof TriggerDefinitionBasicModel
     */
    help?: HelpModel;
    /**
     * The action name.
     * @type {string}
     * @memberof TriggerDefinitionBasicModel
     */
    name: string;
    /**
     * The title
     * @type {string}
     * @memberof TriggerDefinitionBasicModel
     */
    title?: string;
    /**
     * 
     * @type {TriggerTypeModel}
     * @memberof TriggerDefinitionBasicModel
     */
    type: TriggerTypeModel;
}

/**
 * Check if a given object implements the TriggerDefinitionBasicModel interface.
 */
export function instanceOfTriggerDefinitionBasicModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function TriggerDefinitionBasicModelFromJSON(json: any): TriggerDefinitionBasicModel {
    return TriggerDefinitionBasicModelFromJSONTyped(json, false);
}

export function TriggerDefinitionBasicModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerDefinitionBasicModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'help': !exists(json, 'help') ? undefined : HelpModelFromJSON(json['help']),
        'name': json['name'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'type': TriggerTypeModelFromJSON(json['type']),
    };
}

export function TriggerDefinitionBasicModelToJSON(value?: TriggerDefinitionBasicModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'help': HelpModelToJSON(value.help),
        'name': value.name,
        'title': value.title,
        'type': TriggerTypeModelToJSON(value.type),
    };
}

