version: '3.9'

services:
  consul-server1:
    image: hashicorp/consul:1.13.1
    container_name: consul-server1
    restart: always
    volumes:
      - ./consul/server1.json:/consul/config/server1.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

networks:
  consul:
    driver: bridge
