logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7444

spring:
  devtools:
    livereload:
      port: 35731
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
