---
# Conditionally disable springdoc on missing api-docs profile
spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  info:
    git:
      mode: full
    env:
      enabled: true
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
  # Prometheus is the default metrics backend
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60

#openapi:
#  openAPIDefinition:
#    base-path: /api

spring:
  application:
    name: api-gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: configuration-service
          uri: lb://configuration-service-app
          predicates:
          - Path=/api/automation/project-categories/**,/api/automation/project-tags/**,/api/automation/project-workflows/**,/api/automation/projects/**,/api/automation/project-instances/**,/api/automation/project-instance-tags/**,/api/core/action-definitions/**,/api/core/component-definitions/**,/api/core/connection-definitions/**,/api/core/task-dispatcher-definitions/**,/api/core/workflow-tests/**,/api/core/oauth2-properties/**,/api/embedded/integration-categories/**,/api/embedded/integration-tags/**,/api/embedded/integration-workflows/**,/api/embedded/integrations/**
        - id: connection-service
          uri: lb://connection-service-app
          predicates:
            - Path=/api/automation/connection-tags/**,/api/automation/connections/**
        - id: execution-service
          uri: lb://execution-service-app
          predicates:
            - Path=/api/automation/jobs/**,/api/automation/executions/**,/api/automation/tests/**
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      discovery:
        register: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
    date-format: ${bytechef.serialization.date-format}
    time-zone: UTC
  jmx:
    enabled: false
#  main:
#    allow-bean-definition-overriding: true
  output:
    ansi:
      console-available: true
  profiles:
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
  task:
    execution:
      thread-name-prefix: api-gateway-app-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: api-gateway-app-scheduling-
      pool:
        size: 2

server:
  servlet:
    session:
      cookie:
        http-only: true

#####

bytechef:
  discovery-service:
    provider: redis

  serialization:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ
