query identityProviders {
    identityProviders {
        authoritiesClaim
        authorityMappings {
            authority
            externalGroup
        }
        autoProvision
        clientId
        createdBy
        createdDate
        defaultAuthority
        domains
        enabled
        enforced
        id
        issuerUri
        lastModifiedBy
        lastModifiedDate
        mcpEmbedded
        mcpAutomation
        mcpManagement
        metadataUri
        mfaMethod
        mfaRequired
        name
        nameIdFormat
        scopes
        signingCertificate
        type
        validateMcpAudience
    }
}
