dependencies {
    implementation("io.micrometer:micrometer-core")
    implementation("org.springframework.boot:spring-boot-actuator")
    implementation("org.springframework:spring-context")
    implementation("org.springframework:spring-web")
    implementation("org.springframework.boot:spring-boot-actuator")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("org.springframework.data:spring-data-jdbc")
    implementation("org.springframework.security:spring-security-core")
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-repository:atlas-configuration-repository-git"))
    implementation(project(":server:libs:atlas:atlas-coordinator:atlas-coordinator-api"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-api"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-service"))
    implementation(project(":server:libs:config:app-config"))
    implementation(project(":server:libs:core:commons:commons-util"))
    implementation(project(":server:libs:core:tenant:tenant-api"))
    implementation(project(":server:libs:platform:platform-plan:platform-plan-api"))
    implementation(project(":server:libs:platform:platform-rate-limit"))
    implementation(project(":server:libs:platform:platform-api"))
    implementation(project(":server:libs:platform:platform-configuration:platform-configuration-api"))
    implementation(project(":server:libs:platform:platform-connection:platform-connection-api"))
    implementation(project(":server:libs:platform:platform-user:platform-user-api"))
    implementation(project(":server:libs:platform:platform-workflow:platform-workflow-execution:platform-workflow-execution-api"))

    implementation(project(":server:ee:libs:automation:automation-code-workflow-loader"))
    implementation(project(":server:ee:libs:automation:automation-configuration:automation-configuration-api"))
    implementation(project(":server:ee:libs:platform:platform-resource-grant:platform-resource-grant-api"))
    implementation(project(":server:ee:libs:platform:platform-audit:platform-audit-api"))
    implementation(project(":server:ee:libs:platform:platform-code-workflow:platform-code-workflow-file-storage:platform-code-workflow-file-storage-api"))
    implementation(project(":server:ee:libs:platform:platform-configuration:platform-configuration-api"))
    implementation(project(":server:ee:libs:platform:platform-connection:platform-connection-audit"))
    implementation(project(":server:ee:libs:platform:platform-variable:platform-variable-api"))

    testImplementation(rootProject.libs.org.graalvm.polyglot.polyglot)
    testImplementation("org.liquibase:liquibase-core")
    testImplementation("org.springframework.data:spring-data-jdbc")
    testImplementation("org.springframework.security:spring-security-config")
    testImplementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-repository:atlas-configuration-repository-jdbc"))
    testImplementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-service"))
    // PermissionServiceAgentVisibilityTest wires the REAL AiAgentVisibilityProvider/AiAgentOwnershipResolver
    // into this module's PermissionServiceImpl; a stand-in provider would keep it green with the production
    // one deleted. Test-only, and the edge points the legal way round (EE configuration tests -> CE agent).
    testImplementation(project(":server:libs:automation:automation-ai:automation-ai-agent:automation-ai-agent-api"))
    testImplementation(project(":server:libs:automation:automation-ai:automation-ai-agent:automation-ai-agent-service"))
    testImplementation(project(":server:libs:config:jackson-config"))
    testImplementation(project(":server:libs:config:liquibase-config"))
    testImplementation(project(":server:libs:platform:platform-category:platform-category-service"))
    testImplementation(project(":server:libs:platform:platform-component:platform-component-service"))
    testImplementation(project(":server:libs:platform:platform-configuration:platform-configuration-service"))
    testImplementation(project(":server:libs:platform:platform-connection:platform-connection-service"))
    testImplementation(project(":server:libs:platform:platform-security:platform-security-service"))
    testImplementation(project(":server:libs:platform:platform-tag:platform-tag-service"))
    testImplementation(project(":server:libs:test:test-int-support"))

    testImplementation(project(":server:ee:libs:platform:platform-code-workflow:platform-code-workflow-configuration:platform-code-workflow-configuration-service"))
}
