---
# Conditionally disable springdoc on missing api-docs profile
spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---

management:
  endpoints:
    web:
      exposure:
        include:
          '*'
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true

openapi:
  openAPIDefinition:
    base-path: /api

spring:
  application:
    name: api-gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: platform-connections-endpoint
          uri: lb://platform-service-app/
          predicates:
            - Path=/api/connections/**
        - id: platform-caches-endpoint
          uri: lb://platform-service-app/
          predicates:
            - Path=/api/caches/**
        - id: platform-jobs-endpoint
          uri: lb://platform-service-app/
          predicates:
            - Path=/api/jobs/**
        - id: platform-task-executions-endpoint
          uri: lb://platform-service-app/
          predicates:
            - Path=/api/task-executions/**
        - id: platform-workflows-endpoint
          uri: lb://platform-service-app/
          predicates:
            - Path=/api/workflows/**
        - id: worker-definitions-connections-endpoint
          uri: lb://worker-service-app/
          predicates:
            - Path=/api/definitions/connections/**
        - id: coordinator-definitions-task-dispatchers-endpoint
          uri: lb://coordinator-service-app/
          predicates:
            - Path=/api/definitions/task-dispatchers/**
        - id: worker-definitions-components-endpoint
          uri: lb://worker-service-app/
          predicates:
            - Path=/api/definitions/components/**
        - id: coordinator-service
          uri: lb://coordinator-service-app/
          predicates:
            - Path=/coordinator/**
          filters:
            - RewritePath=/coordinator/(?<path>.*), /$\{path}
        - id: platform-service
          uri: lb://platform-service-app/
          predicates:
            - Path=/platform/**
          filters:
            - RewritePath=/platform/(?<path>.*), /$\{path}
        - id: worker-service
          uri: lb://worker-service-app/
          predicates:
            - Path=/worker/**
          filters:
            - RewritePath=/worker/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/service/v3/api-docs/**
          filters:
            - RewritePath=/service/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      discovery:
        register: false
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
    date-format: ${workflow.serialization.date-format}
    time-zone: UTC
  jmx:
    enabled: false
#  main:
#    allow-bean-definition-overriding: true
  output:
    ansi:
      console-available: true
  profiles:
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
  task:
    execution:
      thread-name-prefix: api-gateway-app-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: api-gateway-app-scheduling-
      pool:
        size: 2

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  swagger-ui:
    urls:
      - name: coordinator
        url: /service/v3/api-docs/coordinator
      - name: platform
        url: /service/v3/api-docs/platform
      - name: worker
        url: /service/v3/api-docs/worker

#####

discovery-client:
  provider: property

storage:
  provider: file
  fileStorageDir: /tmp/bytechef/files

workflow:
  message-broker:
    provider: amqp
  persistence:
    provider: jdbc
  serialization:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ
