logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7333

spring:
  devtools:
    livereload:
        port: 35730
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
