spring:
  quartz:
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate

#####

bytechef:
  ai:
    memory:
      provider: inmemory
  datasource:
    url: "jdbc:h2:file:~/.bytechef/bytechef;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=KEY,VALUE,USER"
    username: sa
    password: ""
