apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bytechef-monolith.fullname" . }}-envs
{{- with .Values.env.normal }}
data:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | quote  }}
  {{- end}}
{{- end -}}
