apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytechef-monolith.fullname" . }}-secrets
type: Opaque
{{- with .Values.env.secret }}
data:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
{{- end -}}