/*
 * Copyright 2025 ByteChef
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.bytechef.component.klaviyo.constant;

import static com.bytechef.component.definition.ComponentDsl.array;
import static com.bytechef.component.definition.ComponentDsl.bool;
import static com.bytechef.component.definition.ComponentDsl.dateTime;
import static com.bytechef.component.definition.ComponentDsl.number;
import static com.bytechef.component.definition.ComponentDsl.object;
import static com.bytechef.component.definition.ComponentDsl.string;

import com.bytechef.component.definition.ComponentDsl.ModifiableObjectProperty;

/**
 * @author Marija Horvat
 */
public class KlaviyoConstants {

    public static final String ADDRESS1 = "address1";
    public static final String ADDRESS2 = "address2";
    public static final String ATTRIBUTES = "attributes";
    public static final String CITY = "city";
    public static final String COUNTRY = "country";
    public static final String DATA = "data";
    public static final String EMAIL = "email";
    public static final String FIRST_NAME = "first_name";
    public static final String ID = "id";
    public static final String IMAGE = "image";
    public static final String IP = "ip";
    public static final String LAST_NAME = "last_name";
    public static final String LIST_FIELDS = "listFields";
    public static final String LOCALE = "locale";
    public static final String ORGANIZATION = "organization";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String PROFILE = "profile";
    public static final String PROFILE_ID = "profileId";
    public static final String REGION = "region";
    public static final String SUBSCRIPTION = "subscription";
    public static final String TIMEZONE = "timezone";
    public static final String TITLE = "title";
    public static final String TYPE = "type";
    public static final String ZIP = "zip";

    public static final ModifiableObjectProperty LISTS_OUTPUT_PROPERTY = object()
        .properties(
            array("data")
                .items(
                    object()
                        .properties(
                            string("type")
                                .description("Type of object."),
                            string("id")
                                .description(
                                    "Primary key that uniquely identifies this list. Generated by Klaviyo."),
                            object("attributes")
                                .properties(
                                    string("name")
                                        .description("A helpful name to label the list."),
                                    string("created")
                                        .description(
                                            "Date and time when the list was created, in ISO 8601 format " +
                                                "(YYYY-MM-DDTHH:MM:SS.mmmmmm)."),
                                    string("updated")
                                        .description(
                                            "Date and time when the list was last updated, in ISO 8601 format " +
                                                "(YYYY-MM-DDTHH:MM:SS.mmmmmm)."),
                                    string("opt_in_process")
                                        .description(
                                            "The opt-in process for this list. Could be either 'single_opt_in' or " +
                                                "'double_opt_in'.")),
                            object("links")
                                .properties(
                                    string("self")
                                        .description("URI.")),
                            object("relationships")
                                .properties(
                                    object("profiles")
                                        .properties(
                                            object("links")
                                                .properties(
                                                    string("self")
                                                        .description("URI."),
                                                    string("related")
                                                        .description("URI."))),
                                    object("tags")
                                        .properties(
                                            array("data")
                                                .items(
                                                    object()
                                                        .properties(
                                                            string("type")
                                                                .description("Type."),
                                                            string("id")
                                                                .description("Unique ID."))),
                                            object("links")
                                                .properties(
                                                    string("self")
                                                        .description("URI."),
                                                    string("related")
                                                        .description("URI."))),
                                    object("flow-triggers")
                                        .properties(
                                            array("data")
                                                .items(
                                                    object()
                                                        .properties(
                                                            string("type")
                                                                .description("Type."),
                                                            string("id")
                                                                .description("Unique ID."))),
                                            object("links")
                                                .properties(
                                                    string("self")
                                                        .description("URI."),
                                                    string("related")
                                                        .description("URI.")))))),
            object("links")
                .properties(
                    string("self")
                        .description("URI."),
                    string("first")
                        .description("URI."),
                    string("last")
                        .description("URI."),
                    string("prev")
                        .description("URI."),
                    string("next")
                        .description("URI.")));

    public static final ModifiableObjectProperty PROFILE_OUTPUT_PROPERTY =
        object()
            .properties(
                object("data")
                    .properties(
                        string("type")
                            .description("Type of object."),
                        string("id")
                            .description("Primary key that uniquely identifies this list. Generated by Klaviyo."),
                        object("attributes")
                            .properties(
                                string("email")
                                    .description("Individual's email address."),
                                string("phone_number")
                                    .description("Individual's phone number in E.164 format."),
                                string("external_id")
                                    .description(
                                        "A unique identifier used by customers to associate Klaviyo profiles with " +
                                            "profiles in an external system."),
                                string("anonymous_id")
                                    .description("A unique identifier."),
                                string("first_name")
                                    .description("Individual's first name."),
                                string("last_name")
                                    .description("Individual's last name."),
                                string("organization")
                                    .description("Individual's organization."),
                                string("locale")
                                    .description(
                                        "The locale of the profile, in the IETF BCP 47 language tag format like " +
                                            "(ISO 639-1/2)-(ISO 3166 alpha-2)"),
                                string("title")
                                    .description("Individual's job title."),
                                string("image")
                                    .description("URL pointing to the location of a profile image."),
                                string("created")
                                    .description("Date and time when the profile was created, in ISO 8601 format."),
                                string("updated")
                                    .description(
                                        "Date and time when the profile was last updated, in ISO 8601 format."),
                                string("last_event_date")
                                    .description(
                                        "Date and time of the most recent event the triggered an update to the " +
                                            "profile, in ISO 8601 format."),
                                object("location")
                                    .properties(
                                        string("address1")
                                            .description("First line of street address."),
                                        string("address2")
                                            .description("Second line of street address."),
                                        string("city")
                                            .description("City name."),
                                        string("country")
                                            .description("Country name."),
                                        object("latitude")
                                            .description("Latitude coordinate."),
                                        object("longitude")
                                            .description("Longitude coordinate."),
                                        string("region")
                                            .description("Region within a country, such as state or province."),
                                        string("zip")
                                            .description("Zip code."),
                                        string("timezone")
                                            .description("Time zone name."),
                                        string("ip")
                                            .description("IP address.")),
                                object("properties")
                                    .description(
                                        "An object containing key/value pairs for any custom properties assigned " +
                                            "to this profile."),
                                object("subscriptions")
                                    .properties(
                                        object("email")
                                            .description("The email channel subscription.")
                                            .properties(
                                                object("marketing")
                                                    .description("The email marketing subscription.")
                                                    .properties(
                                                        bool("can_receive_email_marketing")
                                                            .description(
                                                                "Whether or not this profile has implicit consent to " +
                                                                    "receive email marketing. True if it does " +
                                                                    "profile does not have any global suppressions."),
                                                        string("consent")
                                                            .description("The consent status for email marketing."),
                                                        dateTime("consent_timestamp")
                                                            .description(
                                                                "The timestamp when consent was recorded or updated " +
                                                                    "for email marketing, in ISO 8601 format."),
                                                        dateTime("last_updated")
                                                            .description(
                                                                "The timestamp when a field on the email marketing " +
                                                                    "object was last modified."),
                                                        string("method")
                                                            .description(
                                                                "The method by which the profile was subscribed to " +
                                                                    "email marketing."),
                                                        string("method_detail")
                                                            .description(
                                                                "Additional details about the method by which the " +
                                                                    "profile was subscribed to email marketing."),
                                                        string("custom_method_detail")
                                                            .description(
                                                                "Additional detail provided by the caller when the " +
                                                                    "profile was subscribed."),
                                                        bool("double_optin")
                                                            .description(
                                                                "Whether the profile was subscribed to email " +
                                                                    "marketing using a double opt-in."),
                                                        array("suppression")
                                                            .description(
                                                                "The global email marketing suppression for this profile.")
                                                            .items(
                                                                string("reason")
                                                                    .description(
                                                                        "The reason the profile was suppressed."),
                                                                dateTime("timestamp")
                                                                    .description(
                                                                        "The timestamp when the profile was " +
                                                                            "suppressed, in ISO 8601 format.")),
                                                        array("list_suppressions")
                                                            .description("The list suppressions for this profile.")
                                                            .items(
                                                                string("list_id")
                                                                    .description(
                                                                        "The ID of list to which the suppression " +
                                                                            "applies."),
                                                                string("reason")
                                                                    .description(
                                                                        "The reason the profile was suppressed from " +
                                                                            "the list."),
                                                                dateTime("timestamp")
                                                                    .description(
                                                                        "The timestamp when the profile was " +
                                                                            "suppressed from the list, in ISO 8601 format.")))),
                                        object("sms")
                                            .description("The SMS channel subscription.")
                                            .properties(
                                                object("marketing")
                                                    .description("The SMS marketing subscription.")
                                                    .properties(
                                                        bool("can_receive_sms_marketing")
                                                            .description(
                                                                "Whether or not this profile has implicit consent to " +
                                                                    "receive SMS marketing."),
                                                        string("consent")
                                                            .description("The consent status for SMS marketing."),
                                                        dateTime("consent_timestamp")
                                                            .description(
                                                                "The timestamp when consent was recorded or updated " +
                                                                    "for SMS marketing, in ISO 8601 format."),
                                                        string("method")
                                                            .description(
                                                                "The method by which the profile was subscribed to " +
                                                                    "SMS marketing."),
                                                        string("method_detail")
                                                            .description(
                                                                "Additional details about the method by which the " +
                                                                    "profile was subscribed to SMS marketing."),
                                                        dateTime("last_updated")
                                                            .description(
                                                                "The timestamp when the SMS consent record was " +
                                                                    "last modified, in ISO 8601 format.")),
                                                object("transactional")
                                                    .description("The SMS transactional subscription.")
                                                    .properties(
                                                        bool("can_receive_sms_transactional")
                                                            .description(
                                                                "Whether or not this profile has implicit consent " +
                                                                    "to receive transactional SMS."),
                                                        string("consent")
                                                            .description("The consent status for SMS Transactional."),
                                                        dateTime("consent_timestamp")
                                                            .description(
                                                                "The timestamp when consent was recorded or updated " +
                                                                    "for Transactional SMS messaging, in ISO 8601 format."),
                                                        string("method")
                                                            .description(
                                                                "The method by which the profile was subscribed to " +
                                                                    "Transactional SMS messaging."),
                                                        string("method_detail")
                                                            .description(
                                                                "Additional details about the method by which the " +
                                                                    "profile was subscribed to Transactional SMS messaging."),
                                                        dateTime("last_updated")
                                                            .description(
                                                                "The timestamp when the SMS consent record was " +
                                                                    "last modified, in ISO 8601 format."))),
                                        object("mobile_push")
                                            .description("The mobile push channel subscription.")
                                            .properties(
                                                object("marketing")
                                                    .description("The mobile push marketing subscription.")
                                                    .properties(
                                                        bool("can_receive_push_marketing")
                                                            .description(
                                                                "Whether or not this profile has implicit consent " +
                                                                    "to receive mobile push."),
                                                        string("consent")
                                                            .description(
                                                                "The consent status for mobile push marketing."),
                                                        dateTime("consent_timestamp")
                                                            .description(
                                                                "The timestamp when the consent was last changed, " +
                                                                    "in ISO 8601 format.")))),
                                object("predictive_analytics")
                                    .properties(
                                        number("historic_clv")
                                            .description("Total value of all historically placed orders."),
                                        number("predicted_clv")
                                            .description("Predicted value of all placed orders in the next 365 days."),
                                        number("total_clv")
                                            .description("Sum of historic and predicted CLV."),
                                        number("historic_number_of_orders")
                                            .description("Number of already placed orders."),
                                        number("predicted_number_of_orders")
                                            .description("Predicted number of placed orders in the next 365 days"),
                                        number("average_days_between_orders")
                                            .description("Average number of days between orders."),
                                        number("average_order_value")
                                            .description("Average value of placed orders."),
                                        number("churn_probability")
                                            .description("Probability the customer has churned."),
                                        dateTime("expected_date_of_next_order")
                                            .description(
                                                "Expected date of next order, as calculated at the time of their " +
                                                    "most recent order."))),
                        object("links")
                            .properties(
                                string("self")
                                    .description("URI.")),
                        object("relationships")
                            .properties(
                                object("lists")
                                    .properties(
                                        object("data")
                                            .properties(
                                                string("type")
                                                    .description("Type."),
                                                string("id")
                                                    .description("ID.")),
                                        object("links")
                                            .properties(
                                                string("self")
                                                    .description("URI."),
                                                string("related")
                                                    .description("URI."))),
                                object("segments")
                                    .properties(
                                        object("data")
                                            .properties(
                                                string("type")
                                                    .description("Type."),
                                                string("id")
                                                    .description("ID.")),
                                        object("links")
                                            .properties(
                                                string("self")
                                                    .description("URI."),
                                                string("related")
                                                    .description("URI."))),
                                object("push-tokens")
                                    .properties(
                                        object("data")
                                            .properties(
                                                string("type")
                                                    .description("Type."),
                                                string("id")
                                                    .description("ID.")),
                                        object("links")
                                            .properties(
                                                string("self")
                                                    .description("URI."),
                                                string("related")
                                                    .description("URI."))))),
                object("links")
                    .description("Links.")
                    .properties(
                        string("self")
                            .description("URI.")));

    private KlaviyoConstants() {
    }
}
