/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Workflow Execution Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApprovalForm,
} from '../models/index';
import {
    ApprovalFormFromJSON,
    ApprovalFormToJSON,
} from '../models/index';

export interface GetApprovalFormRequest {
    id: string;
}

/**
 * 
 */
export class ApprovalFormApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApprovalForm without sending the request
     */
    async getApprovalFormRequestOpts(requestParameters: GetApprovalFormRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getApprovalForm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/approval-form/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an approval form.
     * Get an approval form
     */
    async getApprovalFormRaw(requestParameters: GetApprovalFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApprovalForm>> {
        const requestOptions = await this.getApprovalFormRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApprovalFormFromJSON(jsonValue));
    }

    /**
     * Get an approval form.
     * Get an approval form
     */
    async getApprovalForm(requestParameters: GetApprovalFormRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApprovalForm> {
        const response = await this.getApprovalFormRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
