/* tslint:disable */
/* eslint-disable */
/**
 * The Automation Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectInstanceWorkflowConnectionModel } from './ProjectInstanceWorkflowConnectionModel';
import {
    ProjectInstanceWorkflowConnectionModelFromJSON,
    ProjectInstanceWorkflowConnectionModelFromJSONTyped,
    ProjectInstanceWorkflowConnectionModelToJSON,
} from './ProjectInstanceWorkflowConnectionModel';

/**
 * Contains configuration and connections required for the execution of a particular project workflow.
 * @export
 * @interface ProjectInstanceWorkflowModel
 */
export interface ProjectInstanceWorkflowModel {
    /**
     * The created by.
     * @type {string}
     * @memberof ProjectInstanceWorkflowModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof ProjectInstanceWorkflowModel
     */
    readonly createdDate?: Date;
    /**
     * The input parameters of an project instance used as workflow input values.
     * @type {{ [key: string]: any; }}
     * @memberof ProjectInstanceWorkflowModel
     */
    inputs?: { [key: string]: any; };
    /**
     * The connections used by a project instance.
     * @type {Array<ProjectInstanceWorkflowConnectionModel>}
     * @memberof ProjectInstanceWorkflowModel
     */
    connections?: Array<ProjectInstanceWorkflowConnectionModel>;
    /**
     * If a workflow is enabled or not in the project instance workflow.
     * @type {boolean}
     * @memberof ProjectInstanceWorkflowModel
     */
    enabled?: boolean;
    /**
     * The id of a project instance.
     * @type {number}
     * @memberof ProjectInstanceWorkflowModel
     */
    readonly id?: number;
    /**
     * The last execution date of a project instance.
     * @type {Date}
     * @memberof ProjectInstanceWorkflowModel
     */
    lastExecutionDate?: Date;
    /**
     * The last modified by.
     * @type {string}
     * @memberof ProjectInstanceWorkflowModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof ProjectInstanceWorkflowModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The id of a project instance.
     * @type {number}
     * @memberof ProjectInstanceWorkflowModel
     */
    projectInstanceId?: number;
    /**
     * The url of a static url used to trigger a workflow.
     * @type {string}
     * @memberof ProjectInstanceWorkflowModel
     */
    staticWebhookUrl?: string;
    /**
     * The id of a workflow.
     * @type {string}
     * @memberof ProjectInstanceWorkflowModel
     */
    workflowId?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectInstanceWorkflowModel
     */
    version?: number;
}

/**
 * Check if a given object implements the ProjectInstanceWorkflowModel interface.
 */
export function instanceOfProjectInstanceWorkflowModel(value: object): boolean {
    return true;
}

export function ProjectInstanceWorkflowModelFromJSON(json: any): ProjectInstanceWorkflowModel {
    return ProjectInstanceWorkflowModelFromJSONTyped(json, false);
}

export function ProjectInstanceWorkflowModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectInstanceWorkflowModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'inputs': json['inputs'] == null ? undefined : json['inputs'],
        'connections': json['connections'] == null ? undefined : ((json['connections'] as Array<any>).map(ProjectInstanceWorkflowConnectionModelFromJSON)),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastExecutionDate': json['lastExecutionDate'] == null ? undefined : (new Date(json['lastExecutionDate'])),
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'projectInstanceId': json['projectInstanceId'] == null ? undefined : json['projectInstanceId'],
        'staticWebhookUrl': json['staticWebhookUrl'] == null ? undefined : json['staticWebhookUrl'],
        'workflowId': json['workflowId'] == null ? undefined : json['workflowId'],
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function ProjectInstanceWorkflowModelToJSON(value?: ProjectInstanceWorkflowModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inputs': value['inputs'],
        'connections': value['connections'] == null ? undefined : ((value['connections'] as Array<any>).map(ProjectInstanceWorkflowConnectionModelToJSON)),
        'enabled': value['enabled'],
        'lastExecutionDate': value['lastExecutionDate'] == null ? undefined : ((value['lastExecutionDate']).toISOString()),
        'projectInstanceId': value['projectInstanceId'],
        'staticWebhookUrl': value['staticWebhookUrl'],
        'workflowId': value['workflowId'],
        '__version': value['version'],
    };
}

