/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Connected User Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConnectedUser,
  CredentialStatus,
  Page,
} from '../models/index';
import {
    ConnectedUserFromJSON,
    ConnectedUserToJSON,
    CredentialStatusFromJSON,
    CredentialStatusToJSON,
    PageFromJSON,
    PageToJSON,
} from '../models/index';

export interface DeleteConnectedUserRequest {
    id: number;
}

export interface EnableConnectedUserRequest {
    id: number;
    enable: boolean;
}

export interface GetConnectedUserRequest {
    id: number;
}

export interface GetConnectedUsersRequest {
    environmentId?: number;
    credentialStatus?: CredentialStatus;
    createDateFrom?: Date;
    createDateTo?: Date;
    integrationId?: number;
    pageNumber?: number;
    search?: string;
}

/**
 * 
 */
export class ConnectedUserApi extends runtime.BaseAPI {

    /**
     * Delete a connected user.
     * Delete a connected user
     */
    async deleteConnectedUserRaw(requestParameters: DeleteConnectedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteConnectedUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/connected-users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a connected user.
     * Delete a connected user
     */
    async deleteConnectedUser(requestParameters: DeleteConnectedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteConnectedUserRaw(requestParameters, initOverrides);
    }

    /**
     * Enable/disable a connected user.
     * Enable/disable a connected user
     */
    async enableConnectedUserRaw(requestParameters: EnableConnectedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling enableConnectedUser().'
            );
        }

        if (requestParameters['enable'] == null) {
            throw new runtime.RequiredError(
                'enable',
                'Required parameter "enable" was null or undefined when calling enableConnectedUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/connected-users/{id}/enable/{enable}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"enable"}}`, encodeURIComponent(String(requestParameters['enable'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Enable/disable a connected user.
     * Enable/disable a connected user
     */
    async enableConnectedUser(requestParameters: EnableConnectedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enableConnectedUserRaw(requestParameters, initOverrides);
    }

    /**
     * Get a connected user.
     * Get a connected user
     */
    async getConnectedUserRaw(requestParameters: GetConnectedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectedUser>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConnectedUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/connected-users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectedUserFromJSON(jsonValue));
    }

    /**
     * Get a connected user.
     * Get a connected user
     */
    async getConnectedUser(requestParameters: GetConnectedUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectedUser> {
        const response = await this.getConnectedUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all connected users.
     * Get all connected users
     */
    async getConnectedUsersRaw(requestParameters: GetConnectedUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        const queryParameters: any = {};

        if (requestParameters['environmentId'] != null) {
            queryParameters['environmentId'] = requestParameters['environmentId'];
        }

        if (requestParameters['credentialStatus'] != null) {
            queryParameters['credentialStatus'] = requestParameters['credentialStatus'];
        }

        if (requestParameters['createDateFrom'] != null) {
            queryParameters['createDateFrom'] = (requestParameters['createDateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['createDateTo'] != null) {
            queryParameters['createDateTo'] = (requestParameters['createDateTo'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['integrationId'] != null) {
            queryParameters['integrationId'] = requestParameters['integrationId'];
        }

        if (requestParameters['pageNumber'] != null) {
            queryParameters['pageNumber'] = requestParameters['pageNumber'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/connected-users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Get all connected users.
     * Get all connected users
     */
    async getConnectedUsers(requestParameters: GetConnectedUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.getConnectedUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
