extend type Query {
    componentPropertyDisplayConditions(
        componentName: String!
        componentVersion: Int!
        operationName: String!
        operationType: ComponentOperationType!
        parameters: Map
    ): Map!

    clusterElementMissingRequiredProperties(
        workflowId: String!
        workflowNodeName: String!
        clusterElementType: String!
        clusterElementWorkflowNodeName: String!
    ): [String!]!

    workflowNodeMissingRequiredProperties(
        workflowId: String!
        workflowNodeName: String!
    ): [String!]!
}

enum ComponentOperationType {
    ACTION
    CLUSTER_ELEMENT
    TRIGGER
}
