dependencies {
    implementation("com.github.ben-manes.caffeine:caffeine")
    implementation("jakarta.annotation:jakarta.annotation-api")
    implementation("org.apache.commons:commons-lang3")
    implementation("org.slf4j:slf4j-api")
    implementation("org.springframework:spring-jdbc")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("redis.clients:jedis")
    implementation("software.amazon.awssdk:s3")
    implementation("tools.jackson.core:jackson-databind")
    implementation(libs.org.springaicommunity.spring.ai.session)
    implementation(project(":server:libs:config:app-config"))
    implementation(project(":server:libs:core:tenant:tenant-api"))
    implementation(project(":server:libs:modules:components:ai:agent:chat-memory:chat-memory-jdbc"))
    implementation(project(":server:libs:modules:components:ai:agent:chat-memory:chat-memory-session"))
    implementation(project(":server:libs:platform:platform-component:platform-component-api"))
    implementation(project(":server:libs:platform:platform-component:platform-component-service"))
    implementation(project(":spring-ai:spring-ai-session-aws"))
    implementation(project(":spring-ai:spring-ai-session-redis"))

    testImplementation("com.h2database:h2")
    testImplementation("org.liquibase:liquibase-core")
    testImplementation("org.postgresql:postgresql")
    testImplementation("org.testcontainers:junit-jupiter")
    testImplementation("org.testcontainers:postgresql")
    testImplementation(project(":server:libs:config:ai-chat-memory-config:ai-chat-memory-aws-config"))
    testImplementation(project(":server:libs:config:ai-chat-memory-config:ai-chat-memory-jdbc-config"))
}
