logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7888

spring:
  devtools:
    livereload:
      port: 35735
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
