/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A trigger/reply-action pair through which an AI Agent can be reached.
 * @export
 * @interface AgentChannelDefinition
 */
export interface AgentChannelDefinition {
    /**
     * The name of the approval cluster element used to gate replies on this channel.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    approvalChannelName?: string;
    /**
     * The path, within the trigger's payload, to the incoming message's attachments.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    attachmentsPath?: string;
    /**
     * The name of the component that declares this channel.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    componentName: string;
    /**
     * The version of the component that declares this channel.
     * @type {number}
     * @memberof AgentChannelDefinition
     */
    componentVersion: number;
    /**
     * The path, within the trigger's payload, to the conversation id.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    conversationIdPath: string;
    /**
     * The description.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    description?: string;
    /**
     * The path, within the trigger's payload, to the incoming message text.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    messagePath: string;
    /**
     * The channel's stored key (matches `ai_agent_channel.channel_type`).
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    name: string;
    /**
     * The name of the reply action, if this channel supports replying.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    replyActionName?: string;
    /**
     * The reply action property that carries outgoing attachments.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    replyAttachmentsProperty?: string;
    /**
     * Reply action parameters mapped from trigger property row keys.
     * @type {{ [key: string]: string; }}
     * @memberof AgentChannelDefinition
     */
    replyChannelParameters?: { [key: string]: string; };
    /**
     * The reply action property that carries the conversation id.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    replyConversationIdProperty?: string;
    /**
     * Reply action parameters fixed to constant values.
     * @type {{ [key: string]: any; }}
     * @memberof AgentChannelDefinition
     */
    replyFixedParameters?: { [key: string]: any; };
    /**
     * The reply action property that carries the outgoing message text.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    replyMessageProperty?: string;
    /**
     * The title
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    title?: string;
    /**
     * The name of the trigger through which incoming messages arrive.
     * @type {string}
     * @memberof AgentChannelDefinition
     */
    triggerName: string;
    /**
     * Fixed parameters applied to the trigger when it is used as an agent channel.
     * @type {{ [key: string]: any; }}
     * @memberof AgentChannelDefinition
     */
    triggerParameters?: { [key: string]: any; };
}

/**
 * Check if a given object implements the AgentChannelDefinition interface.
 */
export function instanceOfAgentChannelDefinition(value: object): value is AgentChannelDefinition {
    if (!('componentName' in value) || value['componentName'] === undefined) return false;
    if (!('componentVersion' in value) || value['componentVersion'] === undefined) return false;
    if (!('conversationIdPath' in value) || value['conversationIdPath'] === undefined) return false;
    if (!('messagePath' in value) || value['messagePath'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('triggerName' in value) || value['triggerName'] === undefined) return false;
    return true;
}

export function AgentChannelDefinitionFromJSON(json: any): AgentChannelDefinition {
    return AgentChannelDefinitionFromJSONTyped(json, false);
}

export function AgentChannelDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentChannelDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'approvalChannelName': json['approvalChannelName'] == null ? undefined : json['approvalChannelName'],
        'attachmentsPath': json['attachmentsPath'] == null ? undefined : json['attachmentsPath'],
        'componentName': json['componentName'],
        'componentVersion': json['componentVersion'],
        'conversationIdPath': json['conversationIdPath'],
        'description': json['description'] == null ? undefined : json['description'],
        'messagePath': json['messagePath'],
        'name': json['name'],
        'replyActionName': json['replyActionName'] == null ? undefined : json['replyActionName'],
        'replyAttachmentsProperty': json['replyAttachmentsProperty'] == null ? undefined : json['replyAttachmentsProperty'],
        'replyChannelParameters': json['replyChannelParameters'] == null ? undefined : json['replyChannelParameters'],
        'replyConversationIdProperty': json['replyConversationIdProperty'] == null ? undefined : json['replyConversationIdProperty'],
        'replyFixedParameters': json['replyFixedParameters'] == null ? undefined : json['replyFixedParameters'],
        'replyMessageProperty': json['replyMessageProperty'] == null ? undefined : json['replyMessageProperty'],
        'title': json['title'] == null ? undefined : json['title'],
        'triggerName': json['triggerName'],
        'triggerParameters': json['triggerParameters'] == null ? undefined : json['triggerParameters'],
    };
}

export function AgentChannelDefinitionToJSON(json: any): AgentChannelDefinition {
    return AgentChannelDefinitionToJSONTyped(json, false);
}

export function AgentChannelDefinitionToJSONTyped(value?: AgentChannelDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approvalChannelName': value['approvalChannelName'],
        'attachmentsPath': value['attachmentsPath'],
        'componentName': value['componentName'],
        'componentVersion': value['componentVersion'],
        'conversationIdPath': value['conversationIdPath'],
        'description': value['description'],
        'messagePath': value['messagePath'],
        'name': value['name'],
        'replyActionName': value['replyActionName'],
        'replyAttachmentsProperty': value['replyAttachmentsProperty'],
        'replyChannelParameters': value['replyChannelParameters'],
        'replyConversationIdProperty': value['replyConversationIdProperty'],
        'replyFixedParameters': value['replyFixedParameters'],
        'replyMessageProperty': value['replyMessageProperty'],
        'title': value['title'],
        'triggerName': value['triggerName'],
        'triggerParameters': value['triggerParameters'],
    };
}

