/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionDefinitionHelp
 */
export interface ConnectionDefinitionHelp {
    /**
     * 
     * @type {string}
     * @memberof ConnectionDefinitionHelp
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDefinitionHelp
     */
    learnMoreUrl?: string;
}

/**
 * Check if a given object implements the ConnectionDefinitionHelp interface.
 */
export function instanceOfConnectionDefinitionHelp(value: object): value is ConnectionDefinitionHelp {
    return true;
}

export function ConnectionDefinitionHelpFromJSON(json: any): ConnectionDefinitionHelp {
    return ConnectionDefinitionHelpFromJSONTyped(json, false);
}

export function ConnectionDefinitionHelpFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionDefinitionHelp {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
        'learnMoreUrl': json['learnMoreUrl'] == null ? undefined : json['learnMoreUrl'],
    };
}

export function ConnectionDefinitionHelpToJSON(json: any): ConnectionDefinitionHelp {
    return ConnectionDefinitionHelpToJSONTyped(json, false);
}

export function ConnectionDefinitionHelpToJSONTyped(value?: ConnectionDefinitionHelp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'learnMoreUrl': value['learnMoreUrl'],
    };
}

