/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteWorkflowTestConfigurationConnectionRequest
 */
export interface DeleteWorkflowTestConfigurationConnectionRequest {
    /**
     * 
     * @type {number}
     * @memberof DeleteWorkflowTestConfigurationConnectionRequest
     */
    connectionId: number;
}

/**
 * Check if a given object implements the DeleteWorkflowTestConfigurationConnectionRequest interface.
 */
export function instanceOfDeleteWorkflowTestConfigurationConnectionRequest(value: object): value is DeleteWorkflowTestConfigurationConnectionRequest {
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    return true;
}

export function DeleteWorkflowTestConfigurationConnectionRequestFromJSON(json: any): DeleteWorkflowTestConfigurationConnectionRequest {
    return DeleteWorkflowTestConfigurationConnectionRequestFromJSONTyped(json, false);
}

export function DeleteWorkflowTestConfigurationConnectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteWorkflowTestConfigurationConnectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionId': json['connectionId'],
    };
}

export function DeleteWorkflowTestConfigurationConnectionRequestToJSON(json: any): DeleteWorkflowTestConfigurationConnectionRequest {
    return DeleteWorkflowTestConfigurationConnectionRequestToJSONTyped(json, false);
}

export function DeleteWorkflowTestConfigurationConnectionRequestToJSONTyped(value?: DeleteWorkflowTestConfigurationConnectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectionId': value['connectionId'],
    };
}

