/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldOption
 */
export interface FieldOption {
    /**
     * 
     * @type {string}
     * @memberof FieldOption
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldOption
     */
    value?: string;
}

/**
 * Check if a given object implements the FieldOption interface.
 */
export function instanceOfFieldOption(value: object): value is FieldOption {
    return true;
}

export function FieldOptionFromJSON(json: any): FieldOption {
    return FieldOptionFromJSONTyped(json, false);
}

export function FieldOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldOption {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function FieldOptionToJSON(json: any): FieldOption {
    return FieldOptionToJSONTyped(json, false);
}

export function FieldOptionToJSONTyped(value?: FieldOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'value': value['value'],
    };
}

