/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines valid property value.
 * @export
 * @interface Option
 */
export interface Option {
    /**
     * Description of the option.
     * @type {string}
     * @memberof Option
     */
    description?: string;
    /**
     * The label of an option.
     * @type {string}
     * @memberof Option
     */
    label?: string;
    /**
     * Can be anything: string, number, array, object, etc. (except `null`)
     * @type {any}
     * @memberof Option
     */
    value?: any | null;
}

/**
 * Check if a given object implements the Option interface.
 */
export function instanceOfOption(value: object): value is Option {
    return true;
}

export function OptionFromJSON(json: any): Option {
    return OptionFromJSONTyped(json, false);
}

export function OptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Option {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'label': json['label'] == null ? undefined : json['label'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function OptionToJSON(json: any): Option {
    return OptionToJSONTyped(json, false);
}

export function OptionToJSONTyped(value?: Option | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'label': value['label'],
        'value': value['value'],
    };
}

