/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyType } from './PropertyType';
import {
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './PropertyType';
import type { Property } from './Property';
import {
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
} from './Property';

/**
 * A task property used in task dispatchers.
 * @export
 * @interface TaskProperty
 */
export interface TaskProperty extends Property {
    /**
     * The task name.
     * @type {string}
     * @memberof TaskProperty
     */
    name?: string;
}



/**
 * Check if a given object implements the TaskProperty interface.
 */
export function instanceOfTaskProperty(value: object): value is TaskProperty {
    return true;
}

export function TaskPropertyFromJSON(json: any): TaskProperty {
    return TaskPropertyFromJSONTyped(json, false);
}

export function TaskPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProperty {
    if (json == null) {
        return json;
    }
    return {
        ...PropertyFromJSONTyped(json, ignoreDiscriminator),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TaskPropertyToJSON(value?: TaskProperty | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...PropertyToJSON(value),
        'name': value['name'],
    };
}

