/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TaskExecution,
} from '../models';
import {
    TaskExecutionFromJSON,
    TaskExecutionToJSON,
} from '../models';

export interface GetJobTaskExecutionsRequest {
    id: string;
}

export interface GetTaskExecutionRequest {
    id: string;
}

/**
 * 
 */
export class TaskExecutionControllerApi extends runtime.BaseAPI {

    /**
     */
    async getJobTaskExecutionsRaw(requestParameters: GetJobTaskExecutionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TaskExecution>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getJobTaskExecutions.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/jobs/{id}/task-executions/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskExecutionFromJSON));
    }

    /**
     */
    async getJobTaskExecutions(requestParameters: GetJobTaskExecutionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TaskExecution>> {
        const response = await this.getJobTaskExecutionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getTaskExecutionRaw(requestParameters: GetTaskExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskExecution>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getTaskExecution.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/task-executions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskExecutionFromJSON(jsonValue));
    }

    /**
     */
    async getTaskExecution(requestParameters: GetTaskExecutionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskExecution> {
        const response = await this.getTaskExecutionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
