query workflowTemplate($id: String!, $sharedWorkflow: Boolean!) {
    workflowTemplate(id: $id, sharedWorkflow: $sharedWorkflow) {
        description
        projectVersion
        publicUrl
        workflow {
            description
            label
            tasks {
                clusterElements
                clusterRoot
                description
                label
                metadata
                name
                node
                parameters
                type
            }
            triggers {
                description
                label
                name
                parameters
                type
            }
        }
        components {
            connection {
                componentName
                version
            }
            icon
            name
            title
            version
        }
    }
}
