/* tslint:disable */
/* eslint-disable */
/**
 * The Embedded Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateIntegrationInstanceConfigurationWorkflowJob200Response
 */
export interface CreateIntegrationInstanceConfigurationWorkflowJob200Response {
    /**
     * The id of an executed job.
     * @type {number}
     * @memberof CreateIntegrationInstanceConfigurationWorkflowJob200Response
     */
    jobId?: number;
}

/**
 * Check if a given object implements the CreateIntegrationInstanceConfigurationWorkflowJob200Response interface.
 */
export function instanceOfCreateIntegrationInstanceConfigurationWorkflowJob200Response(value: object): value is CreateIntegrationInstanceConfigurationWorkflowJob200Response {
    return true;
}

export function CreateIntegrationInstanceConfigurationWorkflowJob200ResponseFromJSON(json: any): CreateIntegrationInstanceConfigurationWorkflowJob200Response {
    return CreateIntegrationInstanceConfigurationWorkflowJob200ResponseFromJSONTyped(json, false);
}

export function CreateIntegrationInstanceConfigurationWorkflowJob200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateIntegrationInstanceConfigurationWorkflowJob200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function CreateIntegrationInstanceConfigurationWorkflowJob200ResponseToJSON(json: any): CreateIntegrationInstanceConfigurationWorkflowJob200Response {
    return CreateIntegrationInstanceConfigurationWorkflowJob200ResponseToJSONTyped(json, false);
}

export function CreateIntegrationInstanceConfigurationWorkflowJob200ResponseToJSONTyped(value?: CreateIntegrationInstanceConfigurationWorkflowJob200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
    };
}

