/* tslint:disable */
/* eslint-disable */
/**
 * Core Definition API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DynamicPropertiesDataSourceModel } from './DynamicPropertiesDataSourceModel';
import {
    DynamicPropertiesDataSourceModelFromJSON,
    DynamicPropertiesDataSourceModelFromJSONTyped,
    DynamicPropertiesDataSourceModelToJSON,
} from './DynamicPropertiesDataSourceModel';
import type { PropertyModel } from './PropertyModel';
import {
    PropertyModelFromJSON,
    PropertyModelFromJSONTyped,
    PropertyModelToJSON,
} from './PropertyModel';
import type { PropertyTypeModel } from './PropertyTypeModel';
import {
    PropertyTypeModelFromJSON,
    PropertyTypeModelFromJSONTyped,
    PropertyTypeModelToJSON,
} from './PropertyTypeModel';

/**
 * A dynamic properties property type.
 * @export
 * @interface DynamicPropertiesPropertyModel
 */
export interface DynamicPropertiesPropertyModel extends PropertyModel {
    /**
     * 
     * @type {DynamicPropertiesDataSourceModel}
     * @memberof DynamicPropertiesPropertyModel
     */
    dynamicPropertiesDataSource?: DynamicPropertiesDataSourceModel;
}

/**
 * Check if a given object implements the DynamicPropertiesPropertyModel interface.
 */
export function instanceOfDynamicPropertiesPropertyModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DynamicPropertiesPropertyModelFromJSON(json: any): DynamicPropertiesPropertyModel {
    return DynamicPropertiesPropertyModelFromJSONTyped(json, false);
}

export function DynamicPropertiesPropertyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicPropertiesPropertyModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...PropertyModelFromJSONTyped(json, ignoreDiscriminator),
        'dynamicPropertiesDataSource': !exists(json, 'dynamicPropertiesDataSource') ? undefined : DynamicPropertiesDataSourceModelFromJSON(json['dynamicPropertiesDataSource']),
    };
}

export function DynamicPropertiesPropertyModelToJSON(value?: DynamicPropertiesPropertyModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...PropertyModelToJSON(value),
        'dynamicPropertiesDataSource': DynamicPropertiesDataSourceModelToJSON(value.dynamicPropertiesDataSource),
    };
}

