dependencies {
    api("org.springframework.data:spring-data-commons")
    api(project(":server:ee:libs:platform:platform-ai:platform-ai-gateway:platform-ai-gateway-api"))
    api(project(":server:ee:libs:platform:platform-ai:platform-ai-gateway-otlp:platform-ai-gateway-otlp-api"))
    api(project(":server:ee:libs:platform:platform-ai:platform-ai-llm-usage:platform-ai-llm-usage-api"))
    api(project(":server:ee:libs:platform:platform-ai:platform-ai-eval:platform-ai-eval-api"))
    api(project(":server:ee:libs:platform:platform-ai:platform-ai-observability:platform-ai-observability-api"))
    api(project(":server:ee:libs:automation:automation-ai:automation-ai-observability:automation-ai-observability-api"))
    api(project(":server:ee:libs:platform:platform-configuration:platform-configuration-api"))

    implementation("com.fasterxml.jackson.core:jackson-annotations")
    implementation("io.projectreactor:reactor-core")
    implementation("jakarta.annotation:jakarta.annotation-api")
    implementation("jakarta.validation:jakarta.validation-api")
    implementation("org.apache.commons:commons-lang3")
    implementation("org.springframework.data:spring-data-jdbc")
    implementation("org.springframework.security:spring-security-core")
    implementation(project(":server:libs:core:commons:commons-data"))
    implementation(project(":server:libs:core:commons:commons-util"))
    implementation(project(":server:libs:core:encryption:encryption-api"))
    implementation(project(":server:libs:platform:platform-security:platform-security-api"))
    implementation(project(":server:libs:platform:platform-security-web:platform-security-web-api"))
    implementation(project(":server:libs:platform:platform-tag:platform-tag-api"))
    implementation(project(":server:libs:platform:platform-user:platform-user-api"))
}
