/* tslint:disable */
/* eslint-disable */
/**
 * The Core Configuration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskDispatcherOperationRequestModel
 */
export interface TaskDispatcherOperationRequestModel {
    /**
     * The parameters of an action.
     * @type {{ [key: string]: object; }}
     * @memberof TaskDispatcherOperationRequestModel
     */
    parameters: { [key: string]: object; };
}

/**
 * Check if a given object implements the TaskDispatcherOperationRequestModel interface.
 */
export function instanceOfTaskDispatcherOperationRequestModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "parameters" in value;

    return isInstance;
}

export function TaskDispatcherOperationRequestModelFromJSON(json: any): TaskDispatcherOperationRequestModel {
    return TaskDispatcherOperationRequestModelFromJSONTyped(json, false);
}

export function TaskDispatcherOperationRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDispatcherOperationRequestModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parameters': json['parameters'],
    };
}

export function TaskDispatcherOperationRequestModelToJSON(value?: TaskDispatcherOperationRequestModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parameters': value.parameters,
    };
}

