/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ComponentDefinitionModel,
} from '../models';
import {
    ComponentDefinitionModelFromJSON,
    ComponentDefinitionModelToJSON,
} from '../models';

/**
 * 
 */
export class ComponentDefinitionsApi extends runtime.BaseAPI {

    /**
     * Returns all component definitions.
     */
    async getComponentDefinitionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ComponentDefinitionModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/definitions/components`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ComponentDefinitionModelFromJSON));
    }

    /**
     * Returns all component definitions.
     */
    async getComponentDefinitions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ComponentDefinitionModel>> {
        const response = await this.getComponentDefinitionsRaw(initOverrides);
        return await response.value();
    }

}
