# This configuration is intended for development purpose
name: bytechef-monitoring
services:
  prometheus:
    image: prom/prometheus:v3.0.1
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    volumes:
      - prometheus:/prometheus
      - ./prometheus/:/etc/prometheus/
    command:
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus-${profile:-dev}.yml
    ports:
      - 9090:9090

  loki:
    image: grafana/loki:3.2.2
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    volumes:
      - ./loki/:/etc/loki/
    command:
      - --config.file=/etc/loki/loki-${profile:-dev}.yml
    ports:
      - 3100:3100

  tempo-init: # See: https://github.com/grafana/tempo/issues/1657#issuecomment-2300351643
    image: &tempoImage grafana/tempo:2.6.1
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo:/var/tempo

  tempo:
    container_name: tempo
    image: *tempoImage
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ '-config.file=/etc/tempo.yml' ]
    depends_on: [ 'tempo-init' ]
    volumes:
      - tempo:/var/tempo
      - ./tempo/tempo-${profile:-dev}.yml:/etc/tempo.yml
    ports:
      - "3200:3200"    # tempo
      - "4318:4318"  # otlp http

  grafana:
    image: grafana/grafana:11.4.0
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/grafana-datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/grafana-dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
volumes:
  prometheus:
    driver: local
  tempo:
    driver: local
