spring:
  application:
    name: configuration-app
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server-app
  config:
    import: optional:configserver:http://localhost:6111
  profiles:
    active: #spring.profiles.active#
  mail:
    host: http://127.0.0.1
    port: 8080
    username: noreply@app.bytechef.io
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
