/* tslint:disable */
/* eslint-disable */
/**
 * Automation Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JobModel } from './JobModel';
import {
    JobModelFromJSON,
    JobModelFromJSONTyped,
    JobModelToJSON,
} from './JobModel';
import type { ProjectInstanceModel } from './ProjectInstanceModel';
import {
    ProjectInstanceModelFromJSON,
    ProjectInstanceModelFromJSONTyped,
    ProjectInstanceModelToJSON,
} from './ProjectInstanceModel';
import type { ProjectModel } from './ProjectModel';
import {
    ProjectModelFromJSON,
    ProjectModelFromJSONTyped,
    ProjectModelToJSON,
} from './ProjectModel';
import type { TaskExecutionModel } from './TaskExecutionModel';
import {
    TaskExecutionModelFromJSON,
    TaskExecutionModelFromJSONTyped,
    TaskExecutionModelToJSON,
} from './TaskExecutionModel';
import type { WorkflowModel } from './WorkflowModel';
import {
    WorkflowModelFromJSON,
    WorkflowModelFromJSONTyped,
    WorkflowModelToJSON,
} from './WorkflowModel';

/**
 * Contains information about execution of one of project workflows.
 * @export
 * @interface WorkflowExecutionModel
 */
export interface WorkflowExecutionModel {
    /**
     * The id of a workflow execution.
     * @type {number}
     * @memberof WorkflowExecutionModel
     */
    readonly id?: number;
    /**
     * 
     * @type {ProjectInstanceModel}
     * @memberof WorkflowExecutionModel
     */
    instance?: ProjectInstanceModel;
    /**
     * 
     * @type {JobModel}
     * @memberof WorkflowExecutionModel
     */
    job?: JobModel;
    /**
     * 
     * @type {ProjectModel}
     * @memberof WorkflowExecutionModel
     */
    project?: ProjectModel;
    /**
     * 
     * @type {Array<TaskExecutionModel>}
     * @memberof WorkflowExecutionModel
     */
    taskExecutions?: Array<TaskExecutionModel>;
    /**
     * 
     * @type {WorkflowModel}
     * @memberof WorkflowExecutionModel
     */
    workflow?: WorkflowModel;
}

/**
 * Check if a given object implements the WorkflowExecutionModel interface.
 */
export function instanceOfWorkflowExecutionModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WorkflowExecutionModelFromJSON(json: any): WorkflowExecutionModel {
    return WorkflowExecutionModelFromJSONTyped(json, false);
}

export function WorkflowExecutionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowExecutionModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'instance': !exists(json, 'instance') ? undefined : ProjectInstanceModelFromJSON(json['instance']),
        'job': !exists(json, 'job') ? undefined : JobModelFromJSON(json['job']),
        'project': !exists(json, 'project') ? undefined : ProjectModelFromJSON(json['project']),
        'taskExecutions': !exists(json, 'taskExecutions') ? undefined : ((json['taskExecutions'] as Array<any>).map(TaskExecutionModelFromJSON)),
        'workflow': !exists(json, 'workflow') ? undefined : WorkflowModelFromJSON(json['workflow']),
    };
}

export function WorkflowExecutionModelToJSON(value?: WorkflowExecutionModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance': ProjectInstanceModelToJSON(value.instance),
        'job': JobModelToJSON(value.job),
        'project': ProjectModelToJSON(value.project),
        'taskExecutions': value.taskExecutions === undefined ? undefined : ((value.taskExecutions as Array<any>).map(TaskExecutionModelToJSON)),
        'workflow': WorkflowModelToJSON(value.workflow),
    };
}

