/* tslint:disable */
/* eslint-disable */
/**
 * The Automation API Platform Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProjectBasic,
} from '../models/index';
import {
    ProjectBasicFromJSON,
    ProjectBasicToJSON,
} from '../models/index';

export interface GetWorkspaceApiCollectionProjectsRequest {
    id: number;
}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI {

    /**
     * Get workspace API collection projects by workspace id.
     * Get workspace API collection projects by workspace id
     */
    async getWorkspaceApiCollectionProjectsRaw(requestParameters: GetWorkspaceApiCollectionProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectBasic>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkspaceApiCollectionProjects().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/workspaces/{id}/api/collections/projects`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectBasicFromJSON));
    }

    /**
     * Get workspace API collection projects by workspace id.
     * Get workspace API collection projects by workspace id
     */
    async getWorkspaceApiCollectionProjects(requestParameters: GetWorkspaceApiCollectionProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectBasic>> {
        const response = await this.getWorkspaceApiCollectionProjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
