/* tslint:disable */
/* eslint-disable */
/**
 * The Automation Configuration Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The git configuration.
 * @export
 * @interface ProjectGitConfiguration
 */
export interface ProjectGitConfiguration {
    /**
     * The project id of a project git configuration.
     * @type {number}
     * @memberof ProjectGitConfiguration
     */
    readonly projectId: number;
    /**
     * The branch.
     * @type {string}
     * @memberof ProjectGitConfiguration
     */
    branch: string;
    /**
     * The enabled.
     * @type {boolean}
     * @memberof ProjectGitConfiguration
     */
    enabled: boolean;
    /**
     * The created by.
     * @type {string}
     * @memberof ProjectGitConfiguration
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof ProjectGitConfiguration
     */
    readonly createdDate?: Date;
    /**
     * The last modified by.
     * @type {string}
     * @memberof ProjectGitConfiguration
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof ProjectGitConfiguration
     */
    readonly lastModifiedDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ProjectGitConfiguration
     */
    version?: number;
}

/**
 * Check if a given object implements the ProjectGitConfiguration interface.
 */
export function instanceOfProjectGitConfiguration(value: object): value is ProjectGitConfiguration {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function ProjectGitConfigurationFromJSON(json: any): ProjectGitConfiguration {
    return ProjectGitConfigurationFromJSONTyped(json, false);
}

export function ProjectGitConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectGitConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'branch': json['branch'],
        'enabled': json['enabled'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'version': json['__version'] == null ? undefined : json['__version'],
    };
}

export function ProjectGitConfigurationToJSON(json: any): ProjectGitConfiguration {
    return ProjectGitConfigurationToJSONTyped(json, false);
}

export function ProjectGitConfigurationToJSONTyped(value?: Omit<ProjectGitConfiguration, 'projectId'|'createdBy'|'createdDate'|'lastModifiedBy'|'lastModifiedDate'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'enabled': value['enabled'],
        '__version': value['version'],
    };
}

