logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7777

spring:
  devtools:
    livereload:
      port: 35734
    restart:
      enabled: true
  h2:
    console:
      enabled: false
  jackson:
    serialization:
      indent-output: true

#####

bytechef:
  datasource:
    url: jdbc:postgresql://localhost:5432/bytechef_execution
    username: postgres
    password: postgres
