/* tslint:disable */
/* eslint-disable */
/**
 * The Automation User API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiKey200ResponseModel
 */
export interface CreateApiKey200ResponseModel {
    /**
     * The secret API key.
     * @type {string}
     * @memberof CreateApiKey200ResponseModel
     */
    secretKey?: string;
}

/**
 * Check if a given object implements the CreateApiKey200ResponseModel interface.
 */
export function instanceOfCreateApiKey200ResponseModel(value: object): boolean {
    return true;
}

export function CreateApiKey200ResponseModelFromJSON(json: any): CreateApiKey200ResponseModel {
    return CreateApiKey200ResponseModelFromJSONTyped(json, false);
}

export function CreateApiKey200ResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKey200ResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'secretKey': json['secretKey'] == null ? undefined : json['secretKey'],
    };
}

export function CreateApiKey200ResponseModelToJSON(value?: CreateApiKey200ResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'secretKey': value['secretKey'],
    };
}

