management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      mode: full
    env:
      enabled: true
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
  # Prometheus is the default metrics backend
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: configuration-service
          uri: lb://configuration-service-app
          predicates:
          - Path=/api/oauth2/authorization-parameters,/api/oauth2-properties,/api/project-categories/**,/api/project-tags/**,/api/project-workflows/**,/api/projects/**,/api/project-instances/**,/api/project-instance-tags/**,/api/action-definitions/**,/api/component-definitions/**,/api/connection-definitions/**,/api/task-dispatcher-definitions/**,/api/integration-categories/**,/api/integration-tags/**,/api/integration-workflows/**,/api/integrations/**
        - id: connection-service
          uri: lb://connection-service-app
          predicates:
            - Path=/api/project-connection-tags/**,/api/project-connections/**
        - id: execution-service
          uri: lb://execution-service-app
          predicates:
            - Path=/api/project-jobs/**,/api/project-workflow-executions/**,/api/project-workflow-tests
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      write-null-map-values: false
    date-format: ${bytechef.serialization.date-format}
    time-zone: UTC
  jmx:
    enabled: false
#  main:
#    allow-bean-definition-overriding: true
  output:
    ansi:
      console-available: true
  profiles:
    active: #spring.profiles.active#
  task:
    execution:
      thread-name-prefix: api-gateway-app-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000

server:
  servlet:
    session:
      cookie:
        http-only: true

#####

bytechef:
  discovery-service:
    provider: redis

  serialization:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ
