/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisplayOption } from './DisplayOption';
import {
    DisplayOptionFromJSON,
    DisplayOptionFromJSONTyped,
    DisplayOptionToJSON,
} from './DisplayOption';
import type { Property } from './Property';
import {
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
} from './Property';
import type { PropertyType } from './PropertyType';
import {
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './PropertyType';

/**
 * 
 * @export
 * @interface OptionProperty
 */
export interface OptionProperty {
    /**
     * 
     * @type {boolean}
     * @memberof OptionProperty
     */
    multipleValues?: boolean;
    /**
     * 
     * @type {Array<Property>}
     * @memberof OptionProperty
     */
    options?: Array<Property>;
    /**
     * 
     * @type {string}
     * @memberof OptionProperty
     */
    description?: string;
    /**
     * 
     * @type {DisplayOption}
     * @memberof OptionProperty
     */
    displayOption?: DisplayOption;
    /**
     * 
     * @type {string}
     * @memberof OptionProperty
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionProperty
     */
    placeholder?: string;
    /**
     * 
     * @type {PropertyType}
     * @memberof OptionProperty
     */
    type?: PropertyType;
}

/**
 * Check if a given object implements the OptionProperty interface.
 */
export function instanceOfOptionProperty(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OptionPropertyFromJSON(json: any): OptionProperty {
    return OptionPropertyFromJSONTyped(json, false);
}

export function OptionPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'multipleValues': !exists(json, 'multipleValues') ? undefined : json['multipleValues'],
        'options': !exists(json, 'options') ? undefined : ((json['options'] as Array<any>).map(PropertyFromJSON)),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'displayOption': !exists(json, 'displayOption') ? undefined : DisplayOptionFromJSON(json['displayOption']),
        'label': !exists(json, 'label') ? undefined : json['label'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'placeholder': !exists(json, 'placeholder') ? undefined : json['placeholder'],
        'type': !exists(json, 'type') ? undefined : PropertyTypeFromJSON(json['type']),
    };
}

export function OptionPropertyToJSON(value?: OptionProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'multipleValues': value.multipleValues,
        'options': value.options === undefined ? undefined : ((value.options as Array<any>).map(PropertyToJSON)),
        'description': value.description,
        'displayOption': DisplayOptionToJSON(value.displayOption),
        'label': value.label,
        'name': value.name,
        'placeholder': value.placeholder,
        'type': PropertyTypeToJSON(value.type),
    };
}

