spring:
  application:
    name: config-server-app
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/apps
  profiles:
    active: dev,native
bytechef:
  discovery-service:
    provider: redis
