/* tslint:disable */
/* eslint-disable */
/**
 * The Platform User API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contains generated key required for calling API.
 * @export
 * @interface ApiKeyModel
 */
export interface ApiKeyModel {
    /**
     * The created by.
     * @type {string}
     * @memberof ApiKeyModel
     */
    readonly createdBy?: string;
    /**
     * The created date.
     * @type {Date}
     * @memberof ApiKeyModel
     */
    readonly createdDate?: Date;
    /**
     * The id of an API key.
     * @type {number}
     * @memberof ApiKeyModel
     */
    readonly id?: number;
    /**
     * The last modified by.
     * @type {string}
     * @memberof ApiKeyModel
     */
    readonly lastModifiedBy?: string;
    /**
     * The last modified date.
     * @type {Date}
     * @memberof ApiKeyModel
     */
    readonly lastModifiedDate?: Date;
    /**
     * The last used date.
     * @type {Date}
     * @memberof ApiKeyModel
     */
    readonly lastUsedDate?: Date;
    /**
     * The name of an API key.
     * @type {string}
     * @memberof ApiKeyModel
     */
    name: string;
    /**
     * The secret API key.
     * @type {string}
     * @memberof ApiKeyModel
     */
    secretKey?: string;
}

/**
 * Check if a given object implements the ApiKeyModel interface.
 */
export function instanceOfApiKeyModel(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function ApiKeyModelFromJSON(json: any): ApiKeyModel {
    return ApiKeyModelFromJSONTyped(json, false);
}

export function ApiKeyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'id': json['id'] == null ? undefined : json['id'],
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'lastUsedDate': json['lastUsedDate'] == null ? undefined : (new Date(json['lastUsedDate'])),
        'name': json['name'],
        'secretKey': json['secretKey'] == null ? undefined : json['secretKey'],
    };
}

export function ApiKeyModelToJSON(value?: ApiKeyModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'secretKey': value['secretKey'],
    };
}

