extend type Query {
    a2aServers: [A2aServer]
    a2aServerTags: [Tag]
}

extend type Mutation {
    createA2aServer(input: CreateA2aServerInput!): A2aServer
    updateA2aServer(id: ID!, input: UpdateA2aServerInput!): A2aServer
    updateA2aServerTags(id: ID!, tags: [TagInput!]!): [Tag]
    deleteA2aServer(id: ID!): Boolean
}

type A2aServer {
    id: ID!
    name: String!
    description: String
    environmentId: ID!
    enabled: Boolean!
    authenticationRequired: Boolean!
    secretKey: String
    lastModifiedDate: Long
    tags: [Tag]
}

input CreateA2aServerInput {
    name: String!
    description: String
    environmentId: ID!
    authenticationRequired: Boolean
}

input UpdateA2aServerInput {
    name: String
    description: String
    enabled: Boolean
    authenticationRequired: Boolean
}
