logging:
  level:
    ROOT: INFO
    com.bytechef: DEBUG

server:
  port: 7666

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/bytechef_connection
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
  devtools:
    livereload:
      port: 35733
    restart:
      enabled: true
  h2:
    console:
      enabled: false
  jackson:
    serialization:
      indent-output: true
