dependencies {
    implementation("com.knuddels:jtokkit")
    implementation("org.springframework:spring-context")
    implementation("org.springframework.ai:spring-ai-mistral-ai")
    implementation("org.springframework.ai:spring-ai-markdown-document-reader")
    implementation("org.springframework.ai:spring-ai-openai")
    implementation("org.springframework.ai:spring-ai-pdf-document-reader")
    implementation("org.springframework.ai:spring-ai-pgvector-store")
    implementation("org.springframework.ai:spring-ai-tika-document-reader")
    implementation(project(":server:libs:config:app-config"))
    implementation(project(":server:libs:core:message:message-broker:message-broker-api"))
    implementation(project(":server:libs:core:message:message-event:message-event-api"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-api"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-file-storage:automation-knowledge-base-file-storage-api"))
    implementation(project(":server:libs:core:tenant:tenant-api"))
}
