spring:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 7111

bytechef:
  mail:
    host: localhost
    port: 1025
  security:
    remember-me:
      key: e48612ba1fd46fa7089fe9f5085d8d164b53ffb2
