management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration
  graphql:
    schema:
      locations: classpath*:graphql/**/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${bytechef.datasource.url}
    username: ${bytechef.datasource.username}
    password: ${bytechef.datasource.password}
    hikari:
      poolName: Hikari
  liquibase:
    contexts: configuration
  task:
    execution:
      thread-name-prefix: configuration-app-task-
