/*
 * Copyright 2025 ByteChef
 *
 * Licensed under the ByteChef Enterprise license (the "Enterprise License");
 * you may not use this file except in compliance with the Enterprise License.
 */

package com.bytechef.ee.ai.hub.artifact;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.bytechef.automation.assetfile.domain.AssetFile;
import com.bytechef.automation.assetfile.domain.AssetFileFormat;
import com.bytechef.automation.assetfile.service.AssetFileFacade;
import com.bytechef.ee.ai.hub.chat.AiHubChatAssetFileService;
import java.io.ByteArrayInputStream;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

/**
 * @version ee
 *
 * @author Ivica Cardic
 */
class DocxArtifactGeneratorTest {

    @Test
    void testGenerateRendersTitleAndSections() throws Exception {
        // Pin the binary contract: the generated bytes must round-trip through POI's reader and contain the title
        // text plus every section heading and paragraph in order. Without the round-trip a regression that emitted
        // valid-looking but empty XWPF (e.g. forgot to call addRun) would still pass a "facade was called" check
        // — checking the actual rendered text is what catches that class of bug.
        AssetFileFacade facade = mock(AssetFileFacade.class);
        AiHubChatAssetFileService linkService = mock(AiHubChatAssetFileService.class);

        AssetFile saved = mock(AssetFile.class);

        when(saved.getId()).thenReturn(42L);
        when(saved.getName()).thenReturn("report.docx");
        when(facade.createBinaryFromAi(
            anyLong(), any(Integer.class), eq("report.docx"),
            eq("application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
            any(byte[].class), eq(AssetFileFormat.DOCX), any(), any(), any()))
                .thenReturn(saved);

        DocxArtifactGenerator generator = new DocxArtifactGenerator(facade, linkService);

        String spec = """
            {
              "title": "Q4 Review",
              "sections": [
                {"heading": "Summary", "paragraphs": ["Revenue rose 12%.", "Gross margin held."]},
                {"heading": "Detail", "paragraphs": ["Subscription drove growth."]}
              ]
            }""";

        GenerationResult result = generator.generate(
            new GenerationRequest(1L, 10L, 0, 7L, (short) 0, "x", "report", spec, null));

        assertThat(result.format()).isEqualTo(AssetFileFormat.DOCX);
        assertThat(result.filename()).isEqualTo("report.docx");

        ArgumentCaptor<byte[]> bytesCaptor = ArgumentCaptor.forClass(byte[].class);

        org.mockito.Mockito.verify(facade)
            .createBinaryFromAi(
                anyLong(), any(Integer.class), any(), any(), bytesCaptor.capture(),
                any(), any(), any(), any());

        try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(bytesCaptor.getValue()))) {
            String fullText = doc.getParagraphs()
                .stream()
                .map(XWPFParagraph::getText)
                .reduce("", (left, right) -> left + "\n" + right);

            assertThat(fullText).contains("Q4 Review");
            assertThat(fullText).contains("Summary");
            assertThat(fullText).contains("Revenue rose 12%.");
            assertThat(fullText).contains("Gross margin held.");
            assertThat(fullText).contains("Detail");
            assertThat(fullText).contains("Subscription drove growth.");
        }
    }

    @Test
    void testGenerateAppendsDocxExtension() {
        AssetFileFacade facade = mock(AssetFileFacade.class);
        AiHubChatAssetFileService linkService = mock(AiHubChatAssetFileService.class);

        AssetFile saved = mock(AssetFile.class);

        when(saved.getId()).thenReturn(42L);
        when(saved.getName()).thenReturn("memo.docx");
        when(facade.createBinaryFromAi(
            anyLong(), any(Integer.class), eq("memo.docx"), any(), any(), any(), any(), any(), any()))
                .thenReturn(saved);

        DocxArtifactGenerator generator = new DocxArtifactGenerator(facade, linkService);

        GenerationResult result = generator.generate(
            new GenerationRequest(
                1L, 10L, 0, 7L, (short) 0, "x", "memo", "{\"title\":\"Memo\"}", null));

        assertThat(result.filename()).isEqualTo("memo.docx");
    }

    @Test
    void testGenerateRejectsMalformedSpec() {
        AssetFileFacade facade = mock(AssetFileFacade.class);
        AiHubChatAssetFileService linkService = mock(AiHubChatAssetFileService.class);

        DocxArtifactGenerator generator = new DocxArtifactGenerator(facade, linkService);

        assertThatThrownBy(() -> generator.generate(
            new GenerationRequest(1L, 10L, 0, 7L, (short) 0, "x", "bad.docx", "{ invalid json", null)))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("DOCX spec is not valid JSON");
    }

    @Test
    void testGenerateAcceptsTitleOnlySpec() {
        // Tolerance invariant: a spec with only a title (no sections) must still produce a valid document — useful
        // for cover pages and one-line memos. Pin so a regression that requires sections=[] doesn't reject this
        // valid use case.
        AssetFileFacade facade = mock(AssetFileFacade.class);
        AiHubChatAssetFileService linkService = mock(AiHubChatAssetFileService.class);

        AssetFile saved = mock(AssetFile.class);

        when(saved.getId()).thenReturn(42L);
        when(saved.getName()).thenReturn("cover.docx");
        when(facade.createBinaryFromAi(
            anyLong(), any(Integer.class), any(), any(), any(byte[].class), any(), any(), any(), any()))
                .thenReturn(saved);

        DocxArtifactGenerator generator = new DocxArtifactGenerator(facade, linkService);

        GenerationResult result = generator.generate(
            new GenerationRequest(
                1L, 10L, 0, 7L, (short) 0, "x", "cover.docx", "{\"title\":\"Cover Page\"}", null));

        assertThat(result.assetFileId()).isEqualTo(42L);
    }
}
