/* tslint:disable */
/* eslint-disable */
/**
 * Automation Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JobBasicModel } from './JobBasicModel';
import {
    JobBasicModelFromJSON,
    JobBasicModelFromJSONTyped,
    JobBasicModelToJSON,
} from './JobBasicModel';
import type { ProjectBasicModel } from './ProjectBasicModel';
import {
    ProjectBasicModelFromJSON,
    ProjectBasicModelFromJSONTyped,
    ProjectBasicModelToJSON,
} from './ProjectBasicModel';
import type { ProjectInstanceBasicModel } from './ProjectInstanceBasicModel';
import {
    ProjectInstanceBasicModelFromJSON,
    ProjectInstanceBasicModelFromJSONTyped,
    ProjectInstanceBasicModelToJSON,
} from './ProjectInstanceBasicModel';
import type { WorkflowModel } from './WorkflowModel';
import {
    WorkflowModelFromJSON,
    WorkflowModelFromJSONTyped,
    WorkflowModelToJSON,
} from './WorkflowModel';

/**
 * Contains information about execution of one of project workflows.
 * @export
 * @interface ProjectWorkflowExecutionBasicModel
 */
export interface ProjectWorkflowExecutionBasicModel {
    /**
     * The id of a workflow execution.
     * @type {number}
     * @memberof ProjectWorkflowExecutionBasicModel
     */
    readonly id?: number;
    /**
     * 
     * @type {ProjectInstanceBasicModel}
     * @memberof ProjectWorkflowExecutionBasicModel
     */
    instance?: ProjectInstanceBasicModel;
    /**
     * 
     * @type {JobBasicModel}
     * @memberof ProjectWorkflowExecutionBasicModel
     */
    job?: JobBasicModel;
    /**
     * 
     * @type {ProjectBasicModel}
     * @memberof ProjectWorkflowExecutionBasicModel
     */
    project?: ProjectBasicModel;
    /**
     * 
     * @type {WorkflowModel}
     * @memberof ProjectWorkflowExecutionBasicModel
     */
    workflow?: WorkflowModel;
}

/**
 * Check if a given object implements the ProjectWorkflowExecutionBasicModel interface.
 */
export function instanceOfProjectWorkflowExecutionBasicModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProjectWorkflowExecutionBasicModelFromJSON(json: any): ProjectWorkflowExecutionBasicModel {
    return ProjectWorkflowExecutionBasicModelFromJSONTyped(json, false);
}

export function ProjectWorkflowExecutionBasicModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectWorkflowExecutionBasicModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'instance': !exists(json, 'instance') ? undefined : ProjectInstanceBasicModelFromJSON(json['instance']),
        'job': !exists(json, 'job') ? undefined : JobBasicModelFromJSON(json['job']),
        'project': !exists(json, 'project') ? undefined : ProjectBasicModelFromJSON(json['project']),
        'workflow': !exists(json, 'workflow') ? undefined : WorkflowModelFromJSON(json['workflow']),
    };
}

export function ProjectWorkflowExecutionBasicModelToJSON(value?: ProjectWorkflowExecutionBasicModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance': ProjectInstanceBasicModelToJSON(value.instance),
        'job': JobBasicModelToJSON(value.job),
        'project': ProjectBasicModelToJSON(value.project),
        'workflow': WorkflowModelToJSON(value.workflow),
    };
}

