query ComponentDefinitionSearch($platformType: PlatformType!, $query: String!) {
    componentDefinitionSearch(platformType: $platformType, query: $query) {
        name
        title
        icon
        description
        version
        actionsCount
        triggersCount
        clusterElementsCount
        clusterRoot
        componentCategories {
            name
            label
        }
        actions {
            name
            title
            description
        }
        triggers {
            name
            title
            description
        }
        clusterElements {
            type {
                name
                label
            }
        }
    }
}
