/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisplayOption } from './DisplayOption';
import {
    DisplayOptionFromJSON,
    DisplayOptionFromJSONTyped,
    DisplayOptionToJSON,
} from './DisplayOption';
import type { PropertyType } from './PropertyType';
import {
    PropertyTypeFromJSON,
    PropertyTypeFromJSONTyped,
    PropertyTypeToJSON,
} from './PropertyType';
import type { TypeProperty } from './TypeProperty';
import {
    TypePropertyFromJSON,
    TypePropertyFromJSONTyped,
    TypePropertyToJSON,
} from './TypeProperty';

/**
 * 
 * @export
 * @interface ArrayProperty
 */
export interface ArrayProperty {
    /**
     * 
     * @type {Array<object>}
     * @memberof ArrayProperty
     */
    defaultValue?: Array<object>;
    /**
     * 
     * @type {Array<TypeProperty>}
     * @memberof ArrayProperty
     */
    items?: Array<TypeProperty>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ArrayProperty
     */
    exampleValue?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof ArrayProperty
     */
    description?: string;
    /**
     * 
     * @type {DisplayOption}
     * @memberof ArrayProperty
     */
    displayOption?: DisplayOption;
    /**
     * 
     * @type {string}
     * @memberof ArrayProperty
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ArrayProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ArrayProperty
     */
    placeholder?: string;
    /**
     * 
     * @type {PropertyType}
     * @memberof ArrayProperty
     */
    type?: PropertyType;
}

/**
 * Check if a given object implements the ArrayProperty interface.
 */
export function instanceOfArrayProperty(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArrayPropertyFromJSON(json: any): ArrayProperty {
    return ArrayPropertyFromJSONTyped(json, false);
}

export function ArrayPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArrayProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultValue': !exists(json, 'defaultValue') ? undefined : json['defaultValue'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(TypePropertyFromJSON)),
        'exampleValue': !exists(json, 'exampleValue') ? undefined : json['exampleValue'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'displayOption': !exists(json, 'displayOption') ? undefined : DisplayOptionFromJSON(json['displayOption']),
        'label': !exists(json, 'label') ? undefined : json['label'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'placeholder': !exists(json, 'placeholder') ? undefined : json['placeholder'],
        'type': !exists(json, 'type') ? undefined : PropertyTypeFromJSON(json['type']),
    };
}

export function ArrayPropertyToJSON(value?: ArrayProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultValue': value.defaultValue,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(TypePropertyToJSON)),
        'exampleValue': value.exampleValue,
        'description': value.description,
        'displayOption': DisplayOptionToJSON(value.displayOption),
        'label': value.label,
        'name': value.name,
        'placeholder': value.placeholder,
        'type': PropertyTypeToJSON(value.type),
    };
}

