/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DisplayOption } from './DisplayOption';
import {
    DisplayOptionFromJSON,
    DisplayOptionFromJSONTyped,
    DisplayOptionToJSON,
} from './DisplayOption';
import type { PropertyOption } from './PropertyOption';
import {
    PropertyOptionFromJSON,
    PropertyOptionFromJSONTyped,
    PropertyOptionToJSON,
} from './PropertyOption';
import type { ValueProperty } from './ValueProperty';
import {
    ValuePropertyFromJSON,
    ValuePropertyFromJSONTyped,
    ValuePropertyToJSON,
} from './ValueProperty';

/**
 * A date property type.
 * @export
 * @interface DateProperty
 */
export interface DateProperty extends ValueProperty {
    /**
     * 
     * @type {string}
     * @memberof DateProperty
     */
    type: string;
}

/**
 * Check if a given object implements the DateProperty interface.
 */
export function instanceOfDateProperty(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function DatePropertyFromJSON(json: any): DateProperty {
    return DatePropertyFromJSONTyped(json, false);
}

export function DatePropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ValuePropertyFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
    };
}

export function DatePropertyToJSON(value?: DateProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ValuePropertyToJSON(value),
        'type': value.type,
    };
}

