query aiHubPersonalAgents($workspaceId: ID!, $environment: Int!) {
    aiHubPersonalAgents(workspaceId: $workspaceId, environment: $environment) {
        id
        workspaceId
        userId
        name
        title
        description
        instructions
        environmentId
        llmProvider
        llmModel
        tools {
            id
            aiHubPersonalAgentId
            componentName
            componentVersion
            operationName
            createdAt
        }
        createdAt
        updatedAt
    }
}
