/* tslint:disable */
/* eslint-disable */
/**
 * The Platform Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The git configuration.
 * @export
 * @interface GitConfiguration
 */
export interface GitConfiguration {
    /**
     * The repository url.
     * @type {string}
     * @memberof GitConfiguration
     */
    url: string;
    /**
     * The username.
     * @type {string}
     * @memberof GitConfiguration
     */
    username: string;
    /**
     * The password.
     * @type {string}
     * @memberof GitConfiguration
     */
    password: string;
}

/**
 * Check if a given object implements the GitConfiguration interface.
 */
export function instanceOfGitConfiguration(value: object): value is GitConfiguration {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function GitConfigurationFromJSON(json: any): GitConfiguration {
    return GitConfigurationFromJSONTyped(json, false);
}

export function GitConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function GitConfigurationToJSON(json: any): GitConfiguration {
    return GitConfigurationToJSONTyped(json, false);
}

export function GitConfigurationToJSONTyped(value?: GitConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'username': value['username'],
        'password': value['password'],
    };
}

