dependencies {
    annotationProcessor(rootProject.libs.com.google.auto.service.auto.service)

    implementation("com.github.ben-manes.caffeine:caffeine")
    implementation(rootProject.libs.com.google.auto.service.auto.service.annotations)
    implementation("org.springframework:spring-webmvc")
    implementation(project(":spring-ai:spring-ag-ui:servers:spring"))
    implementation(project(":server:libs:platform:platform-job-sync"))
    implementation(project(":sdks:backend:java:component-api"))
    implementation(libs.com.github.mizosoft.methanol)
    implementation(libs.org.apache.poi.poi.ooxml)
    implementation(libs.org.jsoup)
    implementation(libs.org.springaicommunity.spring.ai.agent.utils)
    implementation(project(":spring-ai:spring-ai-agent-utils:auto-memory"))
    implementation("org.springframework.ai:spring-ai-tool-search-advisor")
    implementation("org.springframework.ai:spring-ai-tool-search-tool")
    implementation(libs.org.springaicommunity.spring.ai.session)
    implementation(project(":server:libs:modules:components:ai:agent:chat-memory:chat-memory-builtin-session"))
    implementation("io.micrometer:micrometer-core")
    implementation("jakarta.annotation:jakarta.annotation-api")
    implementation("org.springframework.boot:spring-boot-actuator")
    implementation("org.apache.commons:commons-lang3")
    implementation("org.aspectj:aspectjweaver")
    implementation("org.quartz-scheduler:quartz")
    implementation("org.springframework:spring-aop")
    implementation("org.springframework:spring-context")
    implementation("org.springframework:spring-tx")
    implementation("org.springframework.ai:spring-ai-anthropic")
    implementation("org.springframework.ai:spring-ai-commons")
    implementation("org.springframework.ai:spring-ai-mcp")
    implementation("io.modelcontextprotocol.sdk:mcp:${libs.versions.io.modelcontextprotocol.sdk.get()}")
    implementation("com.openai:openai-java-client-okhttp")
    implementation("org.springframework.ai:spring-ai-openai")
    implementation("org.springframework.ai:spring-ai-pgvector-store")
    implementation("org.springframework.ai:spring-ai-autoconfigure-vector-store-pgvector")
    implementation("org.springframework.ai:spring-ai-vector-store-advisor")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("org.springframework.data:spring-data-jdbc")
    implementation("org.springframework.security:spring-security-core")
    implementation(project(":server:libs:platform:platform-ai:platform-ai-api"))
    implementation(project(":server:libs:platform:platform-ai:platform-ai-skill:platform-ai-skill-api"))
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-llm-usage:platform-ai-llm-usage-api"))
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-llm-usage:platform-ai-llm-usage-service"))
    implementation(project(":server:libs:platform:platform-ai:platform-ai-auto-memory:platform-ai-auto-memory-service"))
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-tool-usage:platform-ai-tool-usage-api"))
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-tool-usage:platform-ai-tool-usage-service"))
    implementation(project(":spring-ai:spring-ag-ui:packages:core"))
    implementation(project(":spring-ai:spring-ag-ui:utils:json"))
    implementation(project(":spring-ai:spring-ag-ui:packages:server"))
    implementation(project(":spring-ai:spring-ag-ui:integrations:spring-ai"))
    implementation(project(":server:libs:atlas:atlas-configuration:atlas-configuration-api"))
    implementation(project(":server:libs:atlas:atlas-coordinator:atlas-coordinator-api"))
    implementation(project(":server:libs:atlas:atlas-execution:atlas-execution-api"))
    implementation(project(":server:libs:config:app-config"))
    implementation(project(":server:libs:core:commons:commons-data"))
    implementation(project(":server:libs:core:commons:commons-util"))
    implementation(project(":server:libs:core:encryption:encryption-api"))
    implementation(project(":server:libs:core:tenant:tenant-api"))
    implementation(project(":server:libs:platform:platform-api"))
    implementation(project(":server:libs:platform:platform-component:platform-component-api"))
    implementation(project(":server:libs:platform:platform-configuration:platform-configuration-api"))
    implementation(project(":server:libs:platform:platform-connection:platform-connection-api"))
    implementation(project(":server:libs:platform:platform-scheduler:platform-scheduler-api"))
    implementation(project(":server:libs:platform:platform-user:platform-user-api"))
    implementation(project(":server:libs:platform:platform-webhook:platform-webhook-api"))
    implementation(project(":server:libs:automation:automation-ai:automation-ai-agent:automation-ai-agent-api"))
    implementation(project(":server:libs:automation:automation-asset-file:automation-asset-file-api"))
    implementation(project(":server:libs:automation:automation-configuration:automation-configuration-api"))
    implementation(project(":server:libs:automation:automation-data-table:automation-data-table-api"))
    implementation(project(":server:libs:platform:platform-data-table:platform-data-table-api"))
    implementation(project(":server:libs:automation:automation-knowledge-base:automation-knowledge-base-api"))
    implementation(project(":server:libs:platform:platform-knowledge-base:platform-knowledge-base-api"))
    implementation(project(":server:libs:platform:platform-knowledge-base:platform-knowledge-base-file-storage:platform-knowledge-base-file-storage-api"))
    implementation(project(":server:libs:automation:automation-ai:automation-ai-mcp:automation-ai-mcp-api"))
    implementation(project(":server:libs:automation:automation-workflow:automation-workflow-execution:automation-workflow-execution-api"))
    implementation(project(":server:libs:platform:platform-mcp:platform-mcp-api"))
    implementation(project(":server:libs:automation:automation-ai:automation-ai-tool"))
    implementation(project(":server:libs:platform:platform-ai:platform-ai-tool"))
    implementation(project(":server:ee:libs:automation:automation-ai:automation-ai-tool"))
    implementation(project(":server:libs:ai:ai-api"))
    implementation(project(":server:libs:ai:ai-copilot:ai-copilot-api"))
    implementation(project(":server:libs:ai:ai-copilot:ai-copilot-service"))
    implementation(project(":server:libs:ai:ai-copilot:ai-copilot-tool"))
    implementation(project(":server:ee:libs:automation:automation-ai:automation-ai-copilot"))

    implementation(project(":server:ee:libs:automation:automation-api-platform:automation-api-platform-configuration:automation-api-platform-configuration-api"))
    implementation(project(":server:ee:libs:automation:automation-promotion:automation-promotion-api"))
    implementation(project(":server:ee:libs:ai:ai-copilot:ai-copilot-api"))
    implementation(project(":server:ee:libs:ai:ai-hub:ai-hub-api"))
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-agent:platform-ai-agent-api"))
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-agent:platform-ai-agent-service"))
    // AiGuardrails / AiGuardrailsAdvisor / AiGuardrailMetrics — enforces workspace content guardrails on every AI
    // Hub LLM turn (AiHubSpringAIAgent#resolveChatClient).
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-guardrails:platform-ai-guardrails-service"))
    // WorkspaceSystemPrompts / WorkspaceSystemPromptAdvisor — appends the workspace admin's standing instructions
    // to every AI Hub main-agent LLM turn (AiHubSpringAIAgent#resolveChatClient).
    implementation(project(":server:ee:libs:platform:platform-ai:platform-ai-workspace-prompt:platform-ai-workspace-prompt-service"))
    implementation(project(":server:ee:libs:automation:automation-context-store:automation-context-store-api"))
    implementation(project(":server:ee:libs:platform:platform-audit:platform-audit-api"))
    implementation(project(":server:ee:libs:platform:platform-context-store:platform-context-store-api"))

    testImplementation("io.projectreactor:reactor-test")
    testImplementation("org.assertj:assertj-core")
    testImplementation("org.awaitility:awaitility")
    testImplementation("org.springframework.boot:spring-boot-actuator-autoconfigure")
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.mockito:mockito-core")
    testImplementation("org.mockito:mockito-junit-jupiter")
    testImplementation("org.springframework:spring-webflux")
    testImplementation("org.springframework.boot:spring-boot-autoconfigure")
    testImplementation("org.springframework.data:spring-data-jdbc")
    // AiGatewayInjectionClassifier — referenced by AiHubSpringAIAgentGuardrailsTest to build AiGuardrails directly
    // (the same constructor argument AiGuardrailsAdvisorProviderImpl leaves unset in production).
    testImplementation(project(":server:ee:libs:platform:platform-ai:platform-ai-gateway:platform-ai-gateway-api"))
    testImplementation(project(":server:ee:libs:platform:platform-audit:platform-audit-service"))
    testImplementation(project(":server:libs:automation:automation-asset-file:automation-asset-file-service"))
    testImplementation(project(":server:libs:automation:automation-configuration:automation-configuration-service"))
    testImplementation(project(":server:libs:automation:automation-connection:automation-connection-service"))
    testImplementation(project(":server:libs:config:liquibase-config"))
    testImplementation(project(":server:libs:platform:platform-category:platform-category-service"))
    testImplementation(project(":server:libs:platform:platform-connection:platform-connection-service"))
    testImplementation(project(":server:libs:platform:platform-security:platform-security-service"))
    testImplementation(project(":server:libs:platform:platform-tag:platform-tag-service"))
    testImplementation(project(":server:libs:platform:platform-user:platform-user-service"))
    testImplementation(project(":server:libs:test:test-int-support"))
    testImplementation(project(":server:libs:test:test-support"))
    // IntelligentToolSurfaceParityTest assembles the IntelligentToolCatalog over all three intelligent-tool
    // contributors — CE ai-copilot-service and EE automation-ai-copilot are already implementation deps above;
    // embedded-ai-copilot (EmbeddedIntelligentToolContributorConfiguration / EmbeddedCopilotMcpContributorConfiguration) is
    // needed only for that test.
    testImplementation(project(":server:ee:libs:embedded:embedded-ai:embedded-ai-copilot"))
}
